### ISSUE TITLE
[21pt] Create tool for identifying bad crosswalks

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1000]
Create tool for identifying bad crosswalks

**Comment by mluck** [comment]
I implemented a method to count the number of intersections between NWM streams and DEM-derived reaches, where the idea was that the correct crosswalk should have the highest number of times the two lines intersect.

However, the discrete nature of the DEM-derived reaches (derived from D8 flow direction) can lead to erroneous results depending on how aligned the NWM streams are to the D8 reach directions. For example, in the image below comparing the DEM-derived reach (red) with the NWM stream segments, the upper section (purple) is shorter but has more intersections than the lower section (green) that it's actually crosswalked to.
<img width="165" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/d07a7ea4-a8a6-47b7-925c-f86ab4025855">

**Comment by mluck** [comment]
The current "tree" or "link-based" version of the tool checks for parity of the upstream `feature_id`(s) of each DEM-derived reach:
- the `feature_id`(s) of the upstream reaches as determined from the `HydroID` and `NextDownID` of the current reach
- the `feature_id`(s) of the upstream reaches as determined from the crosswalked `feature_id` of the current reach using the `ID` and `to` fields of the NWM_streams layer

Reaches having the same `feature_id` and upstream `feature_id` are not counted as incorrect crosswalks.
