### ISSUE TITLE
[5pt] Crosswalk issue (array size of 1)

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1014]
During the BED run for fim_4_4_4_0, a significant number of errors were being thrown and we stopped the run. It is unknown how many HUCs had completed versus WIP, but is estimated at 15 to 20. AT that point, there were already six HUCs in error all with the same message.

HUCs that error before being stopped were: 01010009, 01020003, 01050001, 01060001, 01060003, and 01080203.

-----------------------------------------------------------------
```
Finalize catchments and model streams 01080203 0
Fri Oct 20 19:00:20 UTC 2023
Adjusting model reach rating curves
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 1351, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 1252, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "/foss_fim/src/add_crosswalk.py", line 480, in <module>
    add_crosswalk(**args)
  File "/foss_fim/src/utils/shared_functions.py", line 193, in wrapper
    func(*args, **kwargs)
  File "/foss_fim/src/add_crosswalk.py", line 262, in add_crosswalk
    str_order = output_flows.loc[output_flows.HydroID == short_id]['order_'].item()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/base.py", line 350, in item
    raise ValueError("can only convert an array of size 1 to a Python scalar")
ValueError: can only convert an array of size 1 to a Python scalar
```
--------------------
Updated Oct 25:
The culprit ended being around the memory profiler system. That has been spun off to its own seperate PR to fix it, but tis PR also exposes a "less than optimal" fix . In add_crosswalk, it has the following lines:
 for stream_index in output_flows.index:

Generally it is not a great idea to iterate directly against the index of a dataframe in case the dataframe record are changed (added, or deleted). It is generally better to make a quick list of the index and iterate against that. Minor but valuable.

**Comment by RobHanna-NOAA** [comment]
oh strange. Ok. I will play with it. Matt... were you able to get all of the pre-clip files?

**Comment by RobHanna-NOAA** [comment]
ok. I will play with it on one of our prod servers. Maybe something is not quite in sync there.

**Comment by RobHanna-NOAA** [comment]
Strange. I ran a set of just the failed HUCs above and it worked. I am going to restart a BED knowing we can not finish it by Wed to see if it stays stable.

**Comment by RobHanna-NOAA** [comment]
Update: This could be something that is only being seen at scale. It has been running now for a couple of errors and periodically is throwing the same error but with different HUCs. Ones that failed first time around are now passing.  More research is required.  Aborting current BED test run.

**Comment by robgpita-noaa** [comment]
Did PR #1018 close this issue?
