### ISSUE TITLE
[21pt] Upgrade jdk or our base Docker image

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1029]
ITSG reach out saying our docker builds are being done against Java jdk of 11.0.15. That version is now creating security warnings and they need it upgraded to 11.0.18 or higher. Path : /var/lib/docker/overlay2/291c425c996c5c0c28a70a40d6c699bbae371aed64291d1200d191c5db9edc0f/diff/usr/lib/jvm/java-11-openjdk-amd64/

Our current base docker image is `ghcr.io/osgeo/gdal:ubuntu-full-3.4.3`.  After talking to Gautam, he said is is easiest to upgrade out base image to the latestof `[ghcr.io/osgeo/gdal:ubuntu-full-3.8.0](https://github.com/osgeo/gdal/pkgs/container/gdal/144852017?tag=ubuntu-full-3.8.0)`.

If our product has trouble with, there might be a way to get around it, but it might be tricky (unsure).

ALSO: Please update Nikki Peabody in ITSG when implemented so he can retest security tests.

**Comment by robgpita-noaa** [comment]
In a first attempt to update the gdal image used in our `dockerfile`, and issue the `docker build` command, it fails with this stacktrace:

```=> ERROR [stage-1  7/14] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y p7zip-full python3-pip time mpich=3.3.2-2build1 parallel=20161222-1.1 libgeos-dev=3.8.0-1build1 expect=5.45.4-2bui  1.4s
------
 > [stage-1  7/14] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y p7zip-full python3-pip time mpich=3.3.2-2build1 parallel=20161222-1.1 libgeos-dev=3.8.0-1build1 expect=5.45.4-2build1 tmux rsync tzdata:
0.363 
0.363 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
0.363 
0.397 Reading package lists...
1.098 Building dependency tree...
1.227 Reading state information...
1.231 Package parallel is not available, but is referred to by another package.
1.231 This may mean that the package is missing, has been obsoleted, or
1.231 is only available from another source
1.231 
1.231 Package libgeos-dev is not available, but is referred to by another package.
1.231 This may mean that the package is missing, has been obsoleted, or
1.231 is only available from another source
1.231 
1.231 Package mpich is not available, but is referred to by another package.
1.231 This may mean that the package is missing, has been obsoleted, or
1.231 is only available from another source
1.231 
1.237 E: Version '3.3.2-2build1' for 'mpich' was not found
1.237 E: Version '20161222-1.1' for 'parallel' was not found
1.237 E: Version '3.8.0-1build1' for 'libgeos-dev' was not found
------
Dockerfile:74
--------------------
  72 |     
  73 |     RUN apt update --fix-missing
  74 | >>> RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y p7zip-full python3-pip time mpich=3.3.2-2build1 parallel=20161222-1.1 libgeos-dev=3.8.0-1build1 expect=5.45.4-2build1 tmux rsync tzdata
  75 |     
  76 |     RUN apt auto-remove
--------------------
ERROR: failed to solve: process "/bin/sh -c DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y p7zip-full python3-pip time mpich=3.3.2-2build1 parallel=20161222-1.1 libgeos-dev=3.8.0-1build1 expect=5.45.4-2build1 tmux rsync tzdata" did not complete successfully: exit code: 100```

**Comment by RobHanna-NOAA** [comment]
Ya.. this will likely trigger a bunch of package updates both at the docker level and code level.

**Comment by mluck** [comment]
Keep in mind that we previously had an issue using GDAL > 3.4.3 -- it caused unexpected error values in TauDEM's `aread8` function that will need to be verified if GDAL is upgraded. See
- https://github.com/NOAA-OWP/inundation-mapping/issues/840#issuecomment-1511474908
- https://github.com/NOAA-OWP/inundation-mapping/pull/889
- https://github.com/dtarb/TauDEM/issues/254

**Comment by RobHanna-NOAA** [comment]
oh ya.  We might have to dig deeper now. If it continues to be a mess, we might be able to see if we can force the jdk to upgrade as that is the true request from ITSG at this point.

**Comment by RobHanna-NOAA** [comment]
We also don't need to go all the way to the newest GDAL image, we might be able to take a lower one that has a newer jdk. He is asking us to get to jdk 11.0.18 or higher.

**Comment by mluck** [comment]
I tested GDAL up to v3.6.3 and anything above v3.4.3 caused the same issue, so I fixed the GDAL version at 3.4.3. I'm not sure we can go any higher without avoiding the issue. Also, GDAL v.3.6 upgrades the Ubuntu version from 20.04 to 22.04 which bumps the Python version from 3.8.10 to 3.10.6 so other libraries/dependencies may break with v.3.6, which might explain the other errors on the recent Docker build.

**Comment by CarsonPruitt-NOAA** [comment]
Is D8 the only thing that breaks above v3.4.3, or do other things in TauDEM break too? If it's just D8, we could look at switching over to Whitebox since they have an implementation.

**Comment by mluck** [comment]
I'm looking at replacing the TauDEM `aread8` with Whitebox [D8MassFlux](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#d8massflux).

**Comment by mluck** [comment]
Upgrading GDAL from v.3.4.3 to v.3.8.0 caused a number of issues:
- As mentioned in https://github.com/NOAA-OWP/inundation-mapping/issues/840#issuecomment-1511986711, GDAL > v3.4.3 results in erroneous values in TauDEM's `aread8`. This was resolved by replacing `aread8` with the Whitebox equivalent, `d8_mass_flux`, to accumulate the headwaters to derive the DEM reaches. However, `d8_mass_flux` results in a slightly larger (1 pixel) footprint of valid data values which caused other functions to fail. In the end, `rd_depression_filling` (richdem) was also replaced (and richdem removed) by Whitebox `fill_depressions` and TauDEM `flowdir_d8` by Whitebox `d8_pointer`.
- As mentioned in #889, starting with GDAL v.3.6, the Python version was upgraded from 3.8 to 3.10 (v3.10.12 in GDAL v.3.8.0).
    - This caused a dependency issue with a package used in GVAL (error message copied below) and was solved by adding `importlib-metadata` and `typing-extensions` to the Pipfile.

```
Performing Bathymetry Adjustment routine
Traceback (most recent call last):
  File "/foss_fim/src/bathymetric_adjustment.py", line 14, in <module>
    from synthesize_test_cases import progress_bar_handler
  File "/foss_fim/tools/synthesize_test_cases.py", line 17, in <module>
    from run_test_case import Test_Case
  File "/foss_fim/tools/run_test_case.py", line 14, in <module>
    from tools_shared_functions import compute_contingency_stats_from_rasters
  File "/foss_fim/tools/tools_shared_functions.py", line 19, in <module>
    from gval import CatStats
  File "/usr/local/lib/python3.10/dist-packages/gval/__init__.py", line 1, in <module>
    from gval.comparison.compute_comparison import ComparisonProcessing
  File "/usr/local/lib/python3.10/dist-packages/gval/comparison/compute_comparison.py", line 16, in <module>
    from gval.comparison.agreement import _compute_agreement_map
  File "/usr/local/lib/python3.10/dist-packages/gval/comparison/agreement.py", line 24, in <module>
    import dask
  File "/usr/local/lib/python3.10/dist-packages/dask/__init__.py", line 3, in <module>
    from dask.base import (
  File "/usr/local/lib/python3.10/dist-packages/dask/base.py", line 28, in <module>
    from dask._compatibility import EMSCRIPTEN, PY_VERSION
  File "/usr/local/lib/python3.10/dist-packages/dask/_compatibility.py", line 4, in <module>
    from importlib_metadata import entry_points as _entry_points
ModuleNotFoundError: No module named 'importlib_metadata'
```
There are a few new warnings in building the Docker image but they don't seem to cause issues.
```
Installing dependencies from Pipfile.lock (4d82d0)...
Ignoring importlib-resources: markers 'python_version < "3.10"' don't match your environment
Ignoring pkgutil-resolve-name: markers 'python_version < "3.9"' don't match your environment
```
