### ISSUE TITLE
[5pt] Add South Alaska to pre-clip vectors system

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1033]
As the process of adding South Alaska moves forward (see https://github.com/NOAA-OWP/inundation-mapping/issues/792), we will need to update the pre-clip vectors system recently introduced, to have South Alaska files in there. We might not be able to do this potentially depending on progress of HAND processing Alaska Steps.

**Comment by EmilyDeardorff** [comment]
**Calculating headwaters**

I used [src/derive_headwaters.py](https://github.com/NOAA-OWP/inundation-mapping/blob/e7a6b7956322892bbc6a6953b233bde610c6bf5f/src/derive_headwaters.py#L4) to derive the headwaters for the southern Alaska data. The new data is now stored with the rest of the nwm hydrofabric data inputs in EC2.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/19495e76-de71-4ca9-82dc-97a20aa44431)
