### ISSUE TITLE
Test WRDS v3.0

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1040]
Since WRDS is updating to version 3.0 to keep parity with the NWM, we need to test to make sure that the gage metadata and ratings don't have any schema changes.

**Comment by CarsonPruitt-NOAA** [comment]
Use `tools/rating_curve_get_usgs_curves.py` to pull a new set of gage data and check the outputs to make sure there's no glaring issues.

**Comment by robgpita-noaa** [comment]
A work in progress branch exists ([`dev-usgs-gages-new-wrds`](https://github.com/NOAA-OWP/inundation-mapping/tree/dev-usgs-gages-new-wrds)) which updates the `tools/rating_curve_get_usgs_curves.py` script. There were some API errors which are addressed, but might not have been fully resolved.  The last test fails at the call to `get_thresholds()` in `rating_curve_get_usgs_curves.py`:

```
['385433114063901']
Populating..
Attributing mainstems sites
Recasting...
WRDS response error: 
Traceback (most recent call last):
  File "/foss_fim/tools/rating_curve_get_usgs_curves.py", line 459, in <module>
    usgs_rating_to_elev(list_of_gage_sites=list_of_gage_sites, workspace=workspace, sleep_time=sleep_timer)
  File "/foss_fim/tools/rating_curve_get_usgs_curves.py", line 415, in usgs_rating_to_elev
    write_categorical_flow_files(metadata_list, workspace)
  File "/foss_fim/tools/rating_curve_get_usgs_curves.py", line 144, in write_categorical_flow_files
    stages, flows = get_thresholds(threshold_url, select_by='nws_lid', selector=nws_lid, threshold='all')
TypeError: cannot unpack non-iterable NoneType object
```

Notes:

As the WRDS API is internal to the NWC, it is recommended to run and test this script from a NWC environment (`dev1`). 
Additionally, if it is not obvious, to get started, copy the appropriate `.env` in to the `/tools` directory before executing the `/rating_curve_get_usgs_curves.py` script.

**Comment by AliForghani-NOAA** [comment]
@CarsonPruitt-NOAA @EmilyDeardorff @RyanSpies-NOAA 
I updated the wrds tool to get gages data also for Alaska, and the results look reasonable. There are 111 USGS gages in Alaska from which 23 are "acceptable" with their SRC info available in "usgs_rating_curves.csv" file. Below shows acceptable gages:
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/124194814/3bbeda71-0c59-4572-a4c4-1eed03732613)

Is there any specific check we need to do for confirming the veracity of these Alaska gages?

**Comment by RobHanna-NOAA** [comment]
How does this interact with the FIM product?  It doesn't look like it is called as any part of FIM-pipeline. Does it update some input files for fim_pipeline?  Does it run live against post processing? Does it need to run for pre-clips?  Benchmark data? Please update here or better yet, the PR so we know we can start sorting out deployment plans. I usually need a number of lead days prior to merge if it affects inputs or pre-clips.

**Comment by CarsonPruitt-NOAA** [comment]
This change will affect the `usgs_gages.gpkg`, which I don't believe is involved in pre-clipping. [Here is where the file is copied over into the temp HUC directory](https://github.com/NOAA-OWP/inundation-mapping/blob/f30a48627e81c4169a1ed53e46811ba42dbabf2b/src/run_unit_wb.sh#L51).

**Comment by RobHanna-NOAA** [comment]
ok perfect. So we just download it and drop it in the right place in the inputs directory. Oh ya. now I remember Ali showing that to me. Just need to figure out what the acquire and pre-process looks like.  Ali might already have this down so we can just copy it around. Do I have this correct?

**Comment by RobHanna-NOAA** [comment]
And just to confirm, there is no on-going live interaction with WRDS. Just pull down some new data, put it in inputs and we are ready to go.

**Comment by RobHanna-NOAA** [comment]
Deployment Plan:
- rename current usgs_rating_curves.csv to something like "usgs_rating_curves_bk_20240422.csv". 
- replace current usgs_rating_curves.csv with new edition.
- do the same for the usgs_gages.gpkg and catfim_flows.cms.csv.
- Add 4 other files created by tool and place beside the three files mentioned above.
     -  sites_bool_flags.gpkg
     - acceptable_sites_pre.csv
     - acceptable_sites_for_rating_curves.gpkg
     - acceptable_sites_for_rating_curves.csv
- ensure it is copied to all 6 enviros.
