### ISSUE TITLE
Duplicate fid_xs entries (featureid + XS_id) in the ras2fim rating curve points gpkg

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#1046]
Looking at ras2fim release 101 version of the `reformat_ras_rating_curve_points_rel_101.gpkg`, there are ~7k points that have duplicate `fid_xs` attributes. Duplicates appear to have the same attributes and geometry. This could be causing some issues with how the calibration assumes the `fid_xs` is a unique identifer (no duplicates). 

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/69868854/6d59563e-891a-402e-a815-8a83e2aef94c)

**Comment by RobHanna-NOAA** [comment]
Card rebuilt against the ras2fim repo. Now issue [221](https://github.com/NOAA-OWP/ras2fim/issues/221).
