### ISSUE TITLE
[21pt] Create a tool for identifying catchment boundary issues

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1063]
I'm open to suggestions on this tool, but my vision is for this new module to be able to produce inundation and a geopackage of catchment boundary issues given a flow file and a FIM directory. It should be structured similar to the [interpolate_water_surface.py](https://github.com/NOAA-OWP/inundation-mapping/blob/dev-catchment-spillover/tools/interpolate_water_surface.py) module where the catchment boundary function is inserted into the inundation process. 

```
def find_catchment_boundary_issues(
    hydrofabric_dir,
    inundation_tif
):
    ## Your code to identify issues


def inundate_with_catchment_boundaries(
    hydrofabric_dir,
    hucs,
    flow_file,
    inundation_raster,
    output_fileNames=None,
    num_workers=1,
    keep_intermediate=False,
    log_file=None,
    verbose=False,
):
    print("Running Inundation")
    map_file = Inundate_gms(
        hydrofabric_dir=hydrofabric_dir,
        forecast=flow_file,
        num_workers=num_workers,
        hucs=hucs,
        inundation_raster=inundation_raster,
        verbose=verbose,
        log_file=log_file,
        output_fileNames=output_fileNames,
    )
    print("Mosaicking branches together")
    Mosaic_inundation(
        map_file,
        mosaic_attribute='depths_rasters',
        mosaic_output=depths_raster,
        mask=None,
        unit_attribute_name='huc8',
        nodata=elev_raster_ndv,
        workers=1,
        remove_inputs=not keep_intermediate,
        subset=None,
        verbose=verbose,
    )

    print("Determining locations for catchment boundary issues")
    find_catchment_boundary_issues(
        hydrofabric_dir=hydrofabric_dir,
        
    )

if __name__ == '__main__':
    ## This part should be mostly identical to the interpolate_water_surface.py module linked above
    ## with a few tweaks, like replace depth_raster with inundation_raster, etc.
```

**Comment by RileyMcDermott-NOAA** [comment]
Here are some example outputs from the catchment boundary identification tool from HUC 17110010.
With catchment boundary layer on:

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/94fa4204-eb86-441f-ab6d-f26a1d992bb6)


![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/89c58330-5257-4d56-bf2b-6af141c03929)


How view would appear on waterview/FIM review:

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/10a3b68c-ad2f-4403-97d8-8a3413c5fdfd)


![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/6363639c-5fdc-4082-836f-9ff20354c97b)

**Comment by RileyMcDermott-NOAA** [comment]
Updated Catchment Boundary Example Maps:

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/ddad455e-9966-437a-920a-6ffbb92a7661)


![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/eb901fe3-cee2-46d8-ab58-e1bd686021d5)



![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/9f2e24db-a144-4cf2-a5cc-687d6e0ec0a9)



![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/36cafe32-99ea-4631-b713-2b4d34facc6d)
