### ISSUE TITLE
[8pt] Assess removal of unaccredited levee protected area

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1084]
Field personnel have identified a levee protected area that they would like to be un-masked due to the fact that it is not an accredited levee system. We need to fully assess the effects that this will have on the FIM. Since there is a nearby USGS FIM site, this location is a great place for that.

The HUC is `05040006` and levee system ID `3305000018`.

VLab issue:
https://vlab.noaa.gov/redmine/issues/126599

**Comment by CarsonPruitt-NOAA** [comment]
I want to record here the stats on accreditation for all of our levee protected areas:

```
FEMA_ACCREDITATION_RATING
Accredited                                       1107
No Flood Hazard Information Published by FEMA     169
Non Accredited                                   5141
PAL                                               366
Zone A99                                           22
Total...........................................6805
```

**Comment by CarsonPruitt-NOAA** [comment]
Here's the breakdown of square mileage by accreditation:
FEMA_ACCREDITATION_RATING
Accredited                                       46245
No Flood Hazard Information Published by FEMA      161
Non Accredited                                   17731
PAL                                               9567
Zone A99                                           174
Total.........................................73880

**Comment by mluck** [comment]
Here's the comparison with and without the levee-protected area masked
<img width="920" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/df156b49-e5c9-4b27-a394-b2a26ff5f4ff">

**Comment by CarsonPruitt-NOAA** [comment]
Thanks for looking into this Matt. Since this is one of our alpha test sites, `neao1`, can you produce a few maps with the test flows and comparisons between the unmasked HAND and the benchmark data. Specifically I'm looking for evidence (if it exists) that suggests unmasking is a bad idea. E.g. the levee is "breached" at a lower flow in HAND than what the USGS FIM suggests, or HAND inundates totally different areas behind the levee.

**Comment by CarsonPruitt-NOAA** [comment]
It appears that the USGS FIM breaches the levee at major stage.
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/e27dfb56-1f76-4592-96ce-db41189660d3)

**Comment by mluck** [comment]
<img width="933" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/31c8f0f8-b179-486c-ab20-7d20c895c7d5">

**Comment by CarsonPruitt-NOAA** [comment]
I also wanted to check out this levee system (`1405000957`) in Frankfort, KY because we have another USGS FIM site (`fftk2`) as well as drone verification imagery for this location. This levee is accredited, however the USGS FIM indicates that it is "breached" at a very low stage (below Action).

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/36bd7a5f-daf6-4c74-8e1f-64cea892491f)

@mluck, can you replicate your above analysis for this site as well? FYI, this is HUC `05100205`.

**Comment by mluck** [comment]
Here's the second location: ![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/b67a68b6-6fd5-4951-9927-8f0393e8daf6)
