### ISSUE TITLE
[5pt] There were some "bad" AHPS sites that may work with FIM v4.x

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1089]
The `BAD_SITES` variable defined in `/tools/tools_shared_variables.py` contains several sites where the mainstems model from FIM v3.x limited the inundation and caused us to not evaluate there. These sites identified by "mainstems does not extend sufficiently upstream" or "no mainstems nearby" should be re-tested with FIM v4.x.

**Comment by mluck** [comment]
It looks like these issues were not solved by FIM 4 (with the possible exception of `rwdn4`, see below). Some representative inundation agreement images from v4.4.11.0 follow:
<img width="986" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/7cb85b5c-e1cc-4416-a257-ff530eff63de">
<img width="986" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/918bb6fe-33a9-4933-97c4-8c34929fc9e8">
<img width="986" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/0c3a7e41-80cc-4b2e-adb8-e5b305de5f9c">
<img width="986" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/7e94155c-d24a-4bc2-a2c2-dc55ea1e1a13">
<img width="986" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/72914471-ece2-412d-abc2-930097687266">
