### ISSUE TITLE
[5pt] Update HAND calibration for new ras2fim v2 ratings

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1091]

**Comment by RyanSpies-NOAA** [comment]
I have a working feature branch started for this (using data for one HUC), but will wait to submit it until I can test it on all of the newly generated ras2fim outputs. I believe we're still waiting to run the updated ras2fim and produce the necessary rating curve outputs and xsection points for several ras2fim HUCs. 

@RobHanna-NOAA please let me know when we have those new ras2fim output files ready.
