### ISSUE TITLE
[21pt] Develop "healed" HAND workflow that removes hydroconditioning artifacts from depth grids

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1099]
The "healed" HAND workflow uses the difference between the original DEM and the hydroconditioned DEM to "heal" a forecasted depth grid. 

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/4bae9de0-a491-4098-8e6a-203fe05f19a5)
![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/4a26cf88-0247-4291-8884-db626382a077)

Reference: [https://rockyweb.usgs.gov/outgoing/ClaireDeVaughan/SETxFCSTMTG/Jan%2030%202023/20230130-HAND4TEXAS_SETxFCS.pdf](https://rockyweb.usgs.gov/outgoing/ClaireDeVaughan/SETxFCSTMTG/Jan%2030%202023/20230130-HAND4TEXAS_SETxFCS.pdf)

The workflow developed above requires the persistence of a depth-adjustment raster, but I would like to experiment with using the depth-adjustment raster to modify the HAND grid (or REM) directly.

**Comment by CarsonPruitt-NOAA** [comment]
Here's the gdal_calc command that I used to create the prototype maps:
```
subprocess.run(['gdal_calc.py', 
    '-A', dem_meters_tif,
    '-B', dem_thalweg_cond_tif,
    '-C', rem_tif,
    '--outfile', rem_tif,
    '--calc', 'C+(A-B)'])
```
Green is prototype FIM, purple is current FIM
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/94a960be-07af-4e64-9ae1-a514a90043d7)
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/96180fc4-b05c-44ea-9bb4-6b51b0bd64e6)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/93258310-ab13-49b7-ad42-935ba92a20aa)
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/aecdd4b5-1c02-405a-b3fa-936d319b59ae)

**Comment by hhs732** [comment]
The alpha test shows some improvement in FIM for HUC 12090301 :)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/23247850/7406a670-b2b0-4aff-8324-9be6c04407d2)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/23247850/1d83d729-b22d-4737-a88d-4cfef585e244)
