### ISSUE TITLE
[13pt] Abnormal long runtimes for some Alaska HUCs

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1123]
During a full BED for fim_4_4_15_0,  then entire run time jumped dramatically. This is the first run to include Alaska.

Here are the 20 longest runtimes for the 1,900 plus HUCs. humm.. did we lose some HUCs as that sounds wrong, it should be at least 2,180. I will look into that separately.

The list below, the three columns are: HUC number, time in hh:mm, time as a percent

10110201	60:51	60.85
10200101	60:51	60.85
19020101	60:56	60.93
19020201	63:20	63.33
10300102	64:06	64.1
19020103	66:16	66.26
19020800	68:12	68.2
19020302	70:36	70.6
19020302	71:02	71.3
16060008	73:00	73
19020502	79:35	79.58
19020202	84:07	84.11
19020501	89:30	89.5
19020505	89:47	89.78
18100100	90:32	90.53
19020503	99:35	99.58
19020102	133:07	133.11
19020601	243:10	243.16
19020402	282:06	282.1
19020504	290:04	290.6
19020602	462:52	462.86
19020104	642:57	642.95

The HUC prior to 19020102 seem reasonable, but the others are suspicious, especially that last one which is 10.7 hours.

These are times based on using the AWS Step system, which the fargate machines are set at 6 cores (of 8).

We are going to do more tests on those HUCs on Prod which we will use 42 / 48 (7 x difference to see what we get.

**Comment by CarsonPruitt-NOAA** [comment]
Rob, I would love to be able to bring this to leadership's attention. Could you maybe make a comparison of the CONUS HUC processing times to the Alaska HUCs? I'm thinking a boxplot like the one below would really convey our message. If you're too busy to play around with the plotting, could you provide me with the timing data?

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/9ab9a00d-8e80-4330-91d3-74e7d8abef03)

**Comment by EmilyDeardorff** [comment]
Stream line and stream density of HUC 19020401 (the 10-hour HUC) and surrounding HUCs.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/1d546ed5-3cb9-465d-8fb1-95aedaaac807)
![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/71c7d658-c11c-432b-b874-fdb53be36702)

**Comment by RobHanna-NOAA** [comment]
> Rob, I would love to be able to bring this to leadership's attention. Could you maybe make a comparison of the CONUS HUC processing times to the Alaska HUCs? I'm thinking a boxplot like the one below would really convey our message. If you're too busy to play around with the plotting, could you provide me with the timing data?
> 
> ![image](https://private-user-images.githubusercontent.com/90792257/324107483-9ab9a00d-8e80-4330-91d3-74e7d8abef03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTkyMDAsIm5iZiI6MTcxMzU1ODkwMCwicGF0aCI6Ii85MDc5MjI1Ny8zMjQxMDc0ODMtOWFiOWEwMGQtOGU4MC00MzMwLTkxZDMtNzRlN2Q4YWJlZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIwMzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZjZjYzg5ZjMxNTcxMzJmY2Q2OTY0MDQ0NWFiZDZkMTI3MDEwYjVmMmE3MzY2MDlmZDVlOGY2MThiNWQyMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82WvSNvG0wTTOrW7_m8gfqk7-ao_8LiyonD9mjHA4vY)

If you if into the EFS outputs/fim_4_4_15_0/logs/unit, there is a summary file of runtime for all units. That csv  has three columns, huc, runtime in datetime, runtime in time as a percent.

**Comment by RobHanna-NOAA** [comment]
I want to do some experiments on them using just our prod machine. When we run them on our fargates (big aws runs), those machines are small. About the same size as our regular EC2 with only 8 cores and 64GB ram. Maybe those just need more horsepower. I will see what I can test over the weekend and on Monday to see what we can learn.

**Comment by RobHanna-NOAA** [comment]
> I want to do some experiments on them using just our prod machine. When we run them on our fargates (big aws runs), those machines are small. About the same size as our regular EC2 with only 8 cores and 64GB ram. Maybe those just need more horsepower. I will see what I can test over the weekend and on Monday to see what we can learn.

Stranger yet.  The Alaska huc list I ran on Prod was even slower generally speaking (surprisingly). But the trends were the same.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90854818/daba8e00-ae6e-4ac9-9394-dbeee785d367)

**Comment by RobHanna-NOAA** [comment]
And... the BED failed in post processing, but my test alaska set did not fail in post processing ??? See EFS / outputs.

**Comment by CarsonPruitt-NOAA** [comment]
Here's the boxplot for the Alaska HUCs vs CONUS+

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/adeb2f73-7a87-4a6c-88b4-fa31ce87e370)

**Comment by RobHanna-NOAA** [comment]
Looked into number of branches to time ratio:
Pre Alaska:
Most branches: 
Top 5 in order (huc, number of branches)
'21010005':  23.00  : 118,  
'09030001':  40.56     : 116,  
'10300102':   64.10   : 115,  
'03130003':   35.30    : 111,  
'10140201':   46.66  : 106,
Average time is 22 min. (not counting Alaska)

------------------
Alaska number of branches

19020203	33.61	10
19020302	45.46	54
19020301	48.10	39
19020101	60.93	85
19020201	63.33	54
19020103	66.26	94
19020800	68.20	4
19020502	79.58	70
19020202	84.11	66
19020501	89.50	98
19020505	89.78	91
19020503	99.58	29
19020102	133.11	106
19020601	243.16	174
19020402	282.10	44
19020504	290.60	130
19020602	462.86	63
19020104	642.95	135
19020401, (timing not yet know), 29

**Comment by ZahraGhahremani** [comment]
![image](https://github.com/user-attachments/assets/d8e491a0-23f9-467b-bd37-a92adbdaaf38)

**Comment by ZahraGhahremani** [comment]
After rerunning `fim_pipeline` for all HUCs, it seems that  runtime is shorter following the removal of 1st order streams. Here are the results:
![image](https://github.com/user-attachments/assets/5c84e888-8620-4e39-9ed0-16da3102ee2c)


The differences in inundated area between the current dev version and after removal of 1st order streams, as well as the comparison of inundated area between the current dev version and higher GMS, are shown below for each HUC.

HUC `19020104`:
![image](https://github.com/user-attachments/assets/e674988e-ef5d-4486-a301-7331be49b24e)


HUC `19020503`:
![image](https://github.com/user-attachments/assets/8d225b8d-5141-4886-a3dc-f53d0ca0f291)


HUC `19020402`:
![image](https://github.com/user-attachments/assets/6d6a6356-bb53-45d9-8035-c17e333a989e)

HUC `19020602`:
![image](https://github.com/user-attachments/assets/d9a4ee57-5e60-4fd9-91fd-8fb8e9ab030c)

**Comment by ZahraGhahremani** [comment]
I modified the `add_crosswalk.py` script, which uses a nested for loop to update the rating curve for small segments. For HUC `19020104`, the nested loop took 6.3 hours to run. The new changes significantly cut down the runtime without affecting the inundated areas. So, we don’t need to remove any first-order streams
