### ISSUE TITLE
[13pt] Leveed area is so large/long that it is masking too many branches

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1124]
The leveed area at `CAXM7` is masking all FIM products. The leveed area is so long that it is applied to a stream that is not supposed to be masked.

Please see this vlab ticket for details
[https://vlab.noaa.gov/redmine/issues/124281](https://vlab.noaa.gov/redmine/issues/124281)

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/95d14884-c1d0-4611-9bf5-1f32b5117fea)

**Comment by mluck** [comment]
In the image below, the levee in red (other levees in black) is seen as protecting against multiple levelpaths, the mainstem (purple line) and a tributary (green line), so the levee-protected area (dotted area) behind the red levee is masked from those branches.
<img width="485" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/7ddb4660-8554-4e96-a2bd-30c6bb8e75c3">

Closer inspection reveals that the green levelpath doesn't actually cross the red levee but flows around it. This allows for some additional logic to unmask levelpaths from being associated with a levee if they don't cross the levee but they do intersect the leveed area. The image below shows the effect of this change:
<img width="485" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/bf9e1d80-97a5-4952-8fc9-f5875ce850d6">

There is now inundation along the green levelpath that previously had no inundation (see initial issue):
<img width="510" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/fd94ebc5-46cb-4a67-8664-f1c371ee9d2a">
