### ISSUE TITLE
[5pt] projection mismatch for Alaska

### ISSUE THREAD

**Issue by AliForghani-NOAA** [NOAA-OWP/inundation-mapping#1129]
@CarsonPruitt-NOAA @EmilyDeardorff 
In `/src/usgs_gage_crosswalk.py` below, the catchment geodataframe has a different crs compared to the `self.gages` gdf (EPSG 5070 vs 3338) , therefore, no gage is preserved and `usgs_elev_table.csv` output, which is needed for calibration, is not created. 
https://github.com/NOAA-OWP/inundation-mapping/blob/f30a48627e81c4169a1ed53e46811ba42dbabf2b/src/usgs_gage_crosswalk.py#L76-L80

**Comment by EmilyDeardorff** [comment]
This error occurred while testing the FIM pipeline run with the new USGS gages input file (which now includes Alaska).

**Comment by CarsonPruitt-NOAA** [comment]
Good catch there, Ali. It looks like we may be able to fix this by passing the HUC code into that `usgs_gage_crosswalk.py` script and doing a conditional reprojection if it's an Alaska one.

**Comment by EmilyDeardorff** [comment]
After merging in dev, I got an error in the bridge processing for HUC 19020301 (as reflected in  [issue 1148)](https://github.com/NOAA-OWP/inundation-mapping/issues/1148) and hopefully fixed in [PR 1150](https://github.com/NOAA-OWP/inundation-mapping/pull/1150).

```Burn in bridges 19020301 0
/usr/local/lib/python3.10/dist-packages/rasterstats/io.py:335: NodataWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn(
Traceback (most recent call last):
  File "/foss_fim/src/heal_bridges_osm.py", line 146, in <module>
    process_bridges_in_huc(**args)
  File "/foss_fim/src/heal_bridges_osm.py", line 87, in process_bridges_in_huc
    combined_hand_values = np.where(new_hand_values == -999999, hand_grid_vals, new_hand_values)
  File "<__array_function__ internals>", line 180, in where
ValueError: operands could not be broadcast together with shapes (15387,11603) (15323,11555) (15387,11603) 
Command exited with non-zero status 1```
