### ISSUE TITLE
[13pt] Add benchmark data for NWS AHPS sites in Alaska

### ISSUE THREAD

**Issue by mluck** [NOAA-OWP/inundation-mapping#1130]
With the addition of southern Alaska to FIM processing (#1106), we want to add validation data for the NWS AHPS sites there. Those site `lid`s include MNDA2, SKLA2, and SXRA2.

**Comment by mluck** [comment]
There is a script in the repo archive (https://github.com/NOAA-OWP/inundation-mapping/blob/eed7206723faefb29bdb3a6f95a1ce13314ee9e8/tools/preprocess_ahps_nws.py) that was presumably used to create the CONUS NWS benchmark data, although this script doesn't exist in the current repo and is not currently runnable.

**Comment by CarsonPruitt-NOAA** [comment]
The new benchmark data should probably be in the Alaska projection.
