### ISSUE TITLE
[13pt] Check post processing tools for the ability to be re-run on set of processed HUCs

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1141]
One option that has been very valuable for us is the ability to re-run post processing on a processed batch multiple times. While not confirmed, there is a suspicion that it may not work well anymore.  The key will be to eval each post processing tools to see what files it is updating through the HUC folders and branches.  We need to see if it is updating or adding records and how it works to be updated multiple times. I wonder if some files are being appended to and may not look to see if related records need to be updated or added.  Just something to look into . Again. .not confirmed we even have a problem but the option is very important.

Related Issue cards are:
- [1175](https://github.com/NOAA-OWP/inundation-mapping/issues/1175) - Post Processing Logs - Change most to log files and little output
- [1141](https://github.com/NOAA-OWP/inundation-mapping/issues/1141) - Check post processing tools for the ability to be re-run on set of processed HUCs.  (already WIP)
- [1095](https://github.com/NOAA-OWP/inundation-mapping/issues/1095) - Improve Performance for Post-Processing tools
- [1199](https://github.com/NOAA-OWP/inundation-mapping/issues/1199) - Post processing tools and memory / mp use
-

**Comment by CarsonPruitt-NOAA** [comment]
As a reminder, the end goal is for us to be able to run `fim_post_processing.sh` on an output folder without changing the hydroTable data.

This HUC should be your initial testbed because it includes bathymetric adjustment data: `05020005`

For reference, this is where the post-processing routine is called in `fim_pipeline.sh`:
https://github.com/NOAA-OWP/inundation-mapping/blob/dev/fim_pipeline.sh#L126

**Comment by RobHanna-NOAA** [comment]
Good point. I made a backup of the new test 11 set BEFORE applying the post processing. So. maybe I can just spin off 4 copies of that and run post processing on each with different params.  Not sure why I didn't think of that earlier. I will do that.

**Comment by CarsonPruitt-NOAA** [comment]
That's the work-around I usually use if I'm developing or debugging on the post-processing scripts. Zahra is going to start working on this task so we won't have to do that in the future, though.

**Comment by RobHanna-NOAA** [comment]
One of the tricks is that when the pre-processing is run, it makes a copy of the params_tempalte at that time and saves it at the root output folder named "params.env".  It is supposed to (and should it if isn't working), look for that file. So.. if we re-run post with different args, such as Heidi's tests, you have to update the "params.env" and not the "params_tempalte.env"

**Comment by RobHanna-NOAA** [comment]
Actually, we need to double check that the system will works against the "params.env" and not the template. That is a critical part of running fim_pipeline.sh especially in AWS with post processing. Can someone double check this as part of this PR?

**Comment by CarsonPruitt-NOAA** [comment]
I think this line means that we're loading in `params.env` and not `params_template.env`, right?
https://github.com/NOAA-OWP/inundation-mapping/blob/9c1f3af41924a31fa1eddb65177f3e3a96a25064/fim_post_processing.sh#L82

**Comment by RobHanna-NOAA** [comment]
> I think this line means that we're loading in `params.env` and not `params_template.env`, right?
> 
> https://github.com/NOAA-OWP/inundation-mapping/blob/9c1f3af41924a31fa1eddb65177f3e3a96a25064/fim_post_processing.sh#L82

Yup
