### ISSUE TITLE
[5pt] bug in reading Boolean fields of gpkg file using pyogrio engine 

### ISSUE THREAD

**Issue by AliForghani-NOAA** [NOAA-OWP/inundation-mapping#1162]
@CarsonPruitt-NOAA 
This bug occurs in `src/usgs_gage_unit_setup.py`, where 'usgs_gages.gpkg' file is read and the gages within the HUC8 is saved in  'usgs_subset_gages.gpkg' file. The issue is that the Boolean contents of the two columns "acceptable_alt_error" and "acceptable_codes" randomly changes during reading 'usgs_gages.gpkg' file, so, these columns will have wrong contents in 'usgs_subset_gages.gpkg' file. 

The problem seems to be because of a conflict in using `gpd.options.io_engine = "pyogrio"` in `src/usgs_gage_unit_setup.py` file, and setting `export PYOGRIO_USE_ARROW=1` in `/src/bash_variables.env'` file which is loaded during `from utils.shared_variables import PREP_CRS` command in  `src/usgs_gage_unit_setup.py` file. 

Below, I replicate the issue. The correct value of "acceptable_alt_error" for a sample gage ('nws_lid'='CCSA2'), as we can see in QGIS, is True. Below code shows that the content of "acceptable_alt_error" for this sample gage changes after using `os.environ['PYOGRIO_USE_ARROW'] = '1'`.  Note that this error does not happen if we remove either or both of `gpd.options.io_engine = "pyogrio"` and `os.environ['PYOGRIO_USE_ARROW'] = '1'`.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/124194814/1a222649-4aa7-4839-9692-391c4cee70f3)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/124194814/29ef4283-4612-458d-a26e-f27fdd035479)

Because this issue is happening only for the boolean columns, one solution may be simply changing the dtype of "acceptable_alt_error" (and other boolean columns) from Boolean to integer of 0 or 1.

**Comment by CarsonPruitt-NOAA** [comment]
Did you try to prevent the mis-read booleans by specifying the dtype explicitly like this?
`gpd.read_file(usgs_gages_filename, dtype={'acceptable_alt_error': bool})` 
Or do you have to change the pyogrio engine?

**Comment by AliForghani-NOAA** [comment]
I added explicit dtype assignment, and results did not change. but I got below warning:
"/usr/lib/python3.10/contextlib.py:135: RuntimeWarning: driver GPKG does not support open option DTYPE
  return next(self.gen)"

**Comment by mluck** [comment]
It looks like this was due to a bug in GDAL (https://github.com/OSGeo/gdal/issues/8998). The bug is fixed in GDAL v3.8.3.
