### ISSUE TITLE
[1pt] FIM 4.5.0.1 errors from scan

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1167]
During testing of a new tool that scans all log directories looking for the key word of "error", it found a couple hundred with the phrase of "Will not test for outlet backpool error in branch zero" which are perfectly fine.

However, it also found a few other legitimate errors:

./logs/unit/19020602_unit.log:374: KeyError('order_') 
./logs/unit/19020602_unit.log:377: KeyError('order_') 

We might want to look into those someday.

This scan was done against FIM 4.5.0.1. Details can be found at ... fim-data/previous_fim/fim_4_5_0_1/all_errors_from_logs.log

**Comment by CarsonPruitt-NOAA** [comment]
This is more of a warning message and we should probably replace `error` with `issue` in the 2 places in this file to prevent further trips.

[print('Will not test for outlet backpool error.')](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/src/mitigate_branch_outlet_backpool.py#L510-L513)

**Comment by RobHanna-NOAA** [comment]
In light of recent packages upgrades, and the addition of the word error scan tool, no more errors are being recorded in any part of the pipeline flow. We will review again later for warnings which most have been corrected in one way or another now.
