### ISSUE TITLE
[13pt] Bridge inundation tool

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1173]
This should be a new module in `tools/` that can identify the which bridge points in `osm_bridge_centroids.gpkg` are inundated by a given flow file. 

Inputs:
- FIM outputs directory
- Flow file (should be assumed to be the same as the schema for `inundate_mosaic_wrapper`)

Output:
- One geopackage of bridge points with attributes determining threatened / at risk  or neither. A new string field with 3 choices: `threatened`, `at risk`, or 'not at risk' based on whether the forecast breaks the `max_discharge` or `max_discharge75` flow thresholds.

You can get the new version of FIM with the centroids geopackage on dev1 at this location: `/outputs/dev-bridge-pnts`. The `osm_bridge_centroids.gpkg` are at the HUC level, so you will have to iterate through all of the HUCs in a FIM output directory to get all of the inundated bridge points.

**Comment by CarsonPruitt-NOAA** [comment]
This is a useful reference for some similar pandas groupby examples.
https://github.com/NOAA-OWP/inundation-mapping/blob/6fc6d6b45b2eed0b31e57ec472c774127d8327cb/src/aggregate_by_huc.py#L283-L292

**Comment by ZahraGhahremani** [comment]
Here is an example of final output:
![bp](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/e86a85de-20e1-4160-b143-e7baa71dd476)
