### ISSUE TITLE
[21pt] Calculate Stage Variance for AHPS Points

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1193]
With the new caching system in HydroVIS, we've been informed by the field that there are several locations that require a SRC precision of greater than 1-ft intervals. For example, [PEBN4](https://water.noaa.gov/gauges/PEBN4) has less than 2ft between Action and Major stages. Conversely, 1ft stage intervals at [ESSV1](https://water.noaa.gov/gauges/ESSV1) are acceptable.

The goal of this task is to examine the difference between Action and Major (or highest flood stage) at all AHPS locations and figure out what HUC variables (elevation, relief, slope, etc.) may be used to assign a smaller interval for stages (or flows) that require more precision. For example, in HUC `xxxxxxxx` stages 2m through 8m require 0.1 ft intervals, but above 8m stage a 1ft interval is acceptable.

Note that you may have to use stream order to get better results, so an acceptable result could also mean that different stream orders require different variable intervals within the same HUC.

**Comment by ZahraGhahremani** [comment]
There are 3620 unique sites in FIM 4.4.0.0 CatFIM. Of these, 74% have all four thresholds (action, minor, moderate, and major). The table below shows the summary statistics for the differences between these thresholds:

| Difference  | min  | 25%  | 50%  | 75%  |
|-----------|-----------|-----------|-----------|-----------|
| action - minor| -7 | 1 | 2 | 3 |
| minor - moderate | 0 | 1.5 | 2 | 4 |
| moderate - major | 0 | 2 | 2 | 4 |
|action - major | -6 | 5 | 8 | 11 |

Note: The negative values in the action - minor difference indicate cases where the action stage is higher than the minor stage. For example, at sites TSTN6 and SRFC1, the action stage is higher than the minor stage. Specifically, at site TSTN6, the action stage is the highest.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/7d730f37-1359-49b1-b224-5a5e896c65ae)

Only 2%  (50 sites) have less than 2ft between action and major stages. This percentage for action and minor stages is 64%, for minor and moderate is 50%, and for moderate and major is 53%. 

The figures below show the distribution of differences between stages.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/9032f7ef-6de3-431b-b768-4041c48c6e24)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/da9aaa21-3829-4583-a252-55311cf5591d)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/4e20e04c-1008-413c-8cd1-58ccab961a1a)

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/100253864/fd1273fe-84d1-4f99-89cb-9d26f590a5f4)

**Comment by ZahraGhahremani** [comment]
| Interval| Count  | %  |
|-----------|-----------|-----------|
| 0 - 0.1| 8 | 0.3 |
| 0.1- 0.2| 11 | 0.5 | 
| 0.2- 0.25| 0 | 0 | 
|0.25- 0.5| 184 | 8 | 
|0.5 - 1| 22 | 1 |
