### ISSUE TITLE
[5pt] Handle system exits with `FIM_exit_codes`

### ISSUE THREAD

**Issue by mluck** [NOAA-OWP/inundation-mapping#1214]
A few scripts in `fim_pipeline.sh` handle abnormal conditions with `sys.exit()`, `sys.exit(0)`, or `sys.exit(1)`. These should be handled with `FIM_exit_codes` in order to prevent hidden downstream pipeline errors caused by missing files, etc. See #1212 for an example.

**Comment by RobHanna-NOAA** [comment]
Well.. yes, and there are lots of places we do want those errors. Hitting sys.exit (), (0) and (1) are ok if we really want the huc processing to fail that HUC. Other systems pick up the errors for sys.exit(1) and put it in the unit_errors folder. We really only use our special codes so we know how to catch them in key places and log them different (if at all). See examples via filter_catchments_and_add_attributes.py with the search code of `FIM_exit_codes.NO_FLOWLINES_EXIST`, then in `proces_branch.sh` and `fim_process_unit_wb.sh`, it catches status exist codes such as a 61 and decides what to do with them. We can add more codes if we want. Note the best system, but it works.
