### ISSUE TITLE
[3pt] synthesize_test_cases.py annoying error (very large number of them)

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1228]
Soon we will merge [PR 1217](https://github.com/NOAA-OWP/inundation-mapping/pull/1217) with updates for OpenJDK and a bunch of python packages. One of the upgrades is for numpy. 

This has triggered a new warning that creates hundreds and hundreds off on-screen messages, burying potential errors.  

`/foss_fim/tools/overlapping_inundation.py:399: RuntimeWarning: invalid value encountered in cast
  nan_tile = np.array([np.nan]).astype(dtype)[0]`.

I recommend we branch off of 1217 and fix this so they are merged together.

**Comment by mluck** [comment]
This seems to have originated here: https://github.com/numpy/numpy/pull/21437

**Comment by RobHanna-NOAA** [comment]
Needs the following fix:
Changing line 399 in tools/overlapping_inundation.py to nan_tile = np.array([np.nan]) (removed the .astype(dtype)[0] at the end)
