### ISSUE TITLE
[8pt] Remove coordinate accuracy requirement on stage-based CatFIM

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1236]
Remove these 2 lines to test the CatFIM expansion by removing the coordinate accuracy requirement.

https://github.com/NOAA-OWP/inundation-mapping/blob/b6624948fbf558011b12564248fdc321c664d514/tools/generate_categorical_fim.py#L405-L406

**Comment by EmilyDeardorff** [comment]
Just commenting out the above lines didn't increase the number of points let through. It's also looking like we need to comment out this section:

https://github.com/NOAA-OWP/inundation-mapping/blob/b6624948fbf558011b12564248fdc321c664d514/tools/generate_categorical_fim.py#L461-L469

**Comment by EmilyDeardorff** [comment]
Confusingly, I took a look at the UAT flow-based CatFIM outputs for the benchmark (the code WITHOUT the above changes), and it looks like CatFIM is already being generated for points where there is an unacceptable coordinate accuracy code (the red dots). I'm not sure if this is some issue with how I'm viewing the outputs or an issue with the CatFIM data filtering.

**Comment by EmilyDeardorff** [comment]
And a quick check of the CatFIM reviewer shows that at least one of the LIDs that are supposed to be filtered out (LID=NLIM4) is showing up in that version of CatFIM as well... 
![image](https://github.com/user-attachments/assets/1783cc23-b4c6-4baf-9240-528f1dd1fb19)

**Comment by RobHanna-NOAA** [comment]
But does our new code filter out NLIM4 now?

**Comment by EmilyDeardorff** [comment]
It does not, which is fine because our goal was to *loosen the filters*, but it's just weird that there wasn't filtering happening to begin with?

**Comment by RobHanna-NOAA** [comment]
Ya. I wondered that too

**Comment by EmilyDeardorff** [comment]
The above issue was caused because I was testing it on flow-based CatFIM rather than stage-based CatFIM. Whoops!

Testing the code changes on stage-based CatFIM revealed that the code changes effectively increased the number of CatFIM library objects by about double, as shown in the attribute tables in the screenshot below. 

![image](https://github.com/user-attachments/assets/85a73ddb-cdf8-46ed-b5c4-6916c910f9e6)

**Comment by RobHanna-NOAA** [comment]
Yes, however, there is a gotcha that may not yet be factored in. In the CatFIM processing, it attempts to create a record for each site and each magnitude (but not all). Near the end, it rolls up each site so all of it's magnitudes become just one record with multiple status values into the one "status ??" cell. That might account for your increase in record counts.

**Comment by RobHanna-NOAA** [comment]
This may now be covered and included in PR [1165 ](https://github.com/NOAA-OWP/inundation-mapping/pull/1165) but am not sure. The number of sites included went way up now in 1165 and I know there a possible full or partial fix in it it. After PR 1165 is merged to Dev, lets recheck this guy. If more changes are required it can be added to a new branch / PR coming soon which completes the Alaska Integration.
