### ISSUE TITLE
[21pt] Simplify OSM bridges

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1254]
https://github.com/andycarter-pe/tx-bridge/blob/5eb0d18f35d53a180d1bae39921cc26b27dd275c/src/get_osm_bridge_lines_from_shp.py#L89-L92

**Comment by ZahraGhahremani** [comment]
I replaced `feature_from_polygon` with `graph_from_polygon` in the `data/bridges/pull_osm_bridges.py` and compared the results. There are differences in the attribute table fields.

Attribute Table in dev:
![image](https://github.com/user-attachments/assets/4038dfda-e7af-4223-822b-ba0e1562ce88)

Attribute Table after using Simplify:
![image](https://github.com/user-attachments/assets/4cfc72e2-010f-4742-9cb0-a41b47022b7f)

**Comment by CarsonPruitt-NOAA** [comment]
This is a potential solution for #1147.

**Comment by CarsonPruitt-NOAA** [comment]
It seems like these missing bridges may not be roads. Are they railroads?

**Comment by ZahraGhahremani** [comment]
I tried dissolve function to merge touching lines. While it works well for addressing the previous issue, it also combines some bridges that should not be considered as a single bridge based on the current dev version and simplify technique.

Current dev:
![image](https://github.com/user-attachments/assets/e2ffba24-a697-4eae-8c6c-9e514c9ad6cd)

Using dissolve:
![image](https://github.com/user-attachments/assets/7cab3fcf-45b2-4db6-ad2c-c0665bb2e35a)

Using dissolve- bridge lines are not merged based on the current dev version and simplify technique:
![image](https://github.com/user-attachments/assets/f6f06af3-9b31-42dd-ab5c-d3958f98744f)

![image](https://github.com/user-attachments/assets/0961645f-5a14-4aa5-8af4-15aa053021c3)

**Comment by ZahraGhahremani** [comment]
@AliForghani-NOAA The last bridge is in HUC 05030101 (Lat 40.5126 N, long: 80.1354 W).

**Comment by CarsonPruitt-NOAA** [comment]
As part of this task, can you also look into bridges that we're healing that are no longer there. An example was provided by the field for Honeoye Falls, NY ( `HNYN6` / `04130003`).

We need to figure out if our OSM bridge query is pulling "historical" bridges and how we can avoid that.

![Image](https://github.com/user-attachments/assets/e1405b27-f678-4979-8bbc-42a755707a09)

**Comment by ZahraGhahremani** [comment]
These bridges are labeled as "abandoned" bridges and we can filter them out based on their bridge field.
![image](https://github.com/user-attachments/assets/a975a183-7a32-4b37-95f9-6ea3b79d992f)

![image](https://github.com/user-attachments/assets/70bdada4-65d0-444b-8403-bc8c0321ffcc)

**Comment by CarsonPruitt-NOAA** [comment]
Great find!

**Comment by CarsonPruitt-NOAA** [comment]
Can you also check to make sure this bridge is being removed from Churchville, NY in HUC `04130003` (`CHRN6`).
![image](https://github.com/user-attachments/assets/2c2a9e40-a2aa-47c8-a49d-a3a808af628a)

**Comment by ZahraGhahremani** [comment]
Yes. That bridge is an abandoned bridge too.

![image](https://github.com/user-attachments/assets/e5e672a3-e4d5-4041-9490-919bd84d5acf)

![image](https://github.com/user-attachments/assets/c9d88a18-c32b-4b71-a11f-8ef1a38aba22)

**Comment by ZahraGhahremani** [comment]
Here are some examples  from HUC `04130003` after removing `abandoned` bridges.
Red lines are abandoned bridges that don't appear in the new data (green lines).

![image](https://github.com/user-attachments/assets/2f53207c-462f-4fb7-982a-97d1847b8088)

![image](https://github.com/user-attachments/assets/2e122d48-ab5c-49e4-8337-cb90b45c3bf9)
