### ISSUE TITLE
[3pt] Hawaii points disappeared from stage-based CatFIM in release 4.5.2.11

### ISSUE THREAD

**Issue by EmilyDeardorff** [NOAA-OWP/inundation-mapping#1279]
The most recent version of stage-based CatFIM released with FIM version 4.5.2.11 has no mapped points in Hawaii. However, previous versions of CatFIM (such as 4.4.0.0) *do* have mapped points in Hawaii. Track down why these points are no longer being mapped.

**Comment by EmilyDeardorff** [comment]
I compared the CatFIM points for 4.4.0.0 and 4.5.2.11 and, for Hawaii, these are the LIDs that are present in the old version of CatFIM but not the new version: `"olbh1" "hlah1" "wrvh1" "ksfh1" "mkhh1" "wkgh1" "pksh1" "hush1" "whsh1" "hnwh1" "hpoh1"`

The status of these points in the old version is `"ok"` and their status in the new version (where they are not mapped) is `"likely unacceptable gage datum error or accuracy code(s); please see acceptance criteria"`. 

Apparently this code is used when an exception occurs, which is when LID is missing from the table (so the `dem_adj_elevation` value being missing from `usgs_elev_table.csv`).

As a check, LID ksfh1, which mapped correctly in the previous version but not this one, is not found in the `usgs_elev_table.csv` from the current version (`/dev_fim_share/foss_fim/previous_fim/fim_4_4_0_0/20060000/`) but **is** found in the `usgs_elev_table.csv` from FIM 4.5.2.11 (`/dev_fim_share/foss_fim/previous_fim/fim_4_5_2_11/20060000/`).

As an additional note, the `usgs_elev_table.csv` for HUC 20060000 in FIM version 4.4.0.0 is 74 rows long, whereas the table for HUC 20060000 for FIM version 4.5.2.11 is only 8 rows long... so I think there might have been an accidental removal of the sites from this table that resulted in them not being mapped in CatFIM.

![image](https://github.com/user-attachments/assets/4a4bf426-89f2-4e1f-bb0c-caf953f498e0)

![image](https://github.com/user-attachments/assets/f60eca6c-aeaf-4b23-975f-7383995e8dfc)

usgs_elev_table.csv for FIM 4.4.0.0, HUC 20060000 (contains LID ksfh1)
![image](https://github.com/user-attachments/assets/bae2f4e6-d4d7-421c-9490-a1df0d753970)

usgs_elev_table.csv for FIM 4.5.2.11, HUC 20060000 (**does not** contain LID ksfh1)
![image](https://github.com/user-attachments/assets/820c6339-ee58-4072-8ede-3a77d0fee7cf)

**Comment by EmilyDeardorff** [comment]
For Hawaii sites of the usgs_gages.gpkg geopackage, the 'rating' column says 'no.' Would be good to check if there is a rating curve available for these sites in the WRDS API. 

We have updated the gages and rating curves geopackage for the recent version, so we know they've changed since the last time CatFIM was run. 

Only smaller changes have been done to the code that makes the usgs_elev_table.csv.

Also, it would be good to check in Ohio where there are also a lot of dropped sites!

**Comment by EmilyDeardorff** [comment]
The [WRDS API entry for site ksfh1](https://nwcal-wrds.nwc.nws.noaa.gov/api/location/v3.0/rating_curve/16208000/) *does* have a rating curve available.

**Comment by RobHanna-NOAA** [comment]
I ran the hawaii sites against our newest catfim 2.1 as of today and they all failed again. This appears to not a CatFIM problem. More research is required.

**Comment by EmilyDeardorff** [comment]
It seems like a root of this issue is that a bunch of the NWS LIDs in Hawaii were dropped from the USGS elevation table (as mentioned in my first comment). We're opening up another issue, [Issue 1321](https://github.com/NOAA-OWP/inundation-mapping/issues/1321), to approach this because it seems like it may be occurring outside of CatFIM.

**Comment by RobHanna-NOAA** [comment]
I tried a run with 20060000 which I expected the two lids above to pass, but they both failed for other reasons.
KMSH1:No source for rating curve
WRSH1:gage not in HAND usgs gage records

We will see later how other Hawaii site in other hucs fair.

**Comment by RobHanna-NOAA** [comment]
AFter talking to Carson, he mentioned that our usgs_elev_tables are generated in FIM using the usgs_guages.gpkg. That file has been updated since 4.4.0.0, hence the weird site mis-matches. This is a WRDS issue and they will take over.
