### ISSUE TITLE
[13pt] Update 3DEP DEMs

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1281]
Based on the findings in #1257, we should update our DEMs from the USGS 3DEP service to ensure we're using up-to-date data.

Instead of doing a full domain download and replace, it may be better to take a targeted approach to only download the areas that have been updated. Here's an example of a way we could accomplish that.
`aws s3 ls s3://prd-tnm/StagedProducts/Elevation/13/TIFF/current/ --recursive`

**Comment by RobHanna-NOAA** [comment]
We can not download just one part, well... not easily.  We have our tool to download DEMs but it does a handful of other things such as some cropping, downloads with critical params, creates polys and the vrt.  You really can not replace just small parts.  It is pretty easy to run our acquire 3dep script and isn't overly slow on a prod machine.  I can kick off a full new set in the next few days.

**Comment by CarsonPruitt-NOAA** [comment]
That's probably a better choice anyway to make sure we don't accidentally miss any files.

**Comment by RobHanna-NOAA** [comment]
ya. and with the critical other download args we need and post download processing, you would find is it incredibly difficult to do it without our acquire tool. There is more processing in our tool than one might think.  The hardest part of any input  changes is not the acquire, it is the processing and careful process of getting all right files, vrts, dems and poly's to all 5 / 6 environments at the right time. ie) Hopefully not overwriting anything. :)

**Comment by mluck** [comment]
We should revisit #887 with the new DEMs

**Comment by RobHanna-NOAA** [comment]
Good point. When I have this done plus the pre-clips, we can recheck this before merge.
