### ISSUE TITLE
[5pt] hand_4_5_8_0 unit error: 02030201_unit.log

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1294]
During the hand_4_5_8_0 UAT run, it picked up one unit error.

-----------------------------------------------------------------
Using CRS: EPSG:5070
Mon Sep 16 15:25:40 UTC 2024

-----------------------------------------------------------------
Copying staged wbd and .gpkg files from /data/inputs/pre_clip_huc8/20240702/02030201

-----------------------------------------------------------------
Generating Level Paths for 02030201
Sorry, no streams exist and processing can not continue. This could be an empty file.
Command exited with non-zero status 60
	Command being timed: "/foss_fim/src/run_unit_wb.sh"

==========================
This can be found at /efs..../previous_fim/hand_4_5_8_0/unit_errors/02030201_unit.log

This might be correct, but seems odd.

**Comment by mluck** [comment]
That is correct. This is a coastal HUC and there no levelpaths inside the HUC (brown); however, there is one levelpath within the 5km WBD buffer (red).
![image](https://github.com/user-attachments/assets/77ee5add-9e82-4988-ba9f-0e358a7e3449)
