### ISSUE TITLE
[8pt] eval plots for nws not showing 19020302 huc

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1295]
When I  look at the `data/previous_fim/hand_4_5_8_0/eval/nws/comp/nws_comp_analyzed_data.csv`, I do not find any records for our single AK huc of `19020302`.  I backchecked to 4.5.2.11 and it was not there. However, synthesis test case is adding records for it in test_case folder. ie) `data/test_cases/nws_test_cases/19020302_nws/official_versions/hand_4_5_8_0/

Is this correct?

**Comment by CarsonPruitt-NOAA** [comment]
I wasn't able to replicate this issue. I copied `19020302` into a new FIM directory and re-ran synthesize_test_cases along with eval_plots without any issues.

![image](https://github.com/user-attachments/assets/dede4f38-0d32-463e-8fb8-cb012363f324)
![image](https://github.com/user-attachments/assets/80830128-aba6-4164-bd44-a0a616a0ba9f)

**Comment by RobHanna-NOAA** [comment]
hummm. ok. cool. Must have mis-read that file. Thanks Carson
