### ISSUE TITLE
[5pt] HUC 04270101 doesn't have any bridges

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1305]
![Image](https://github.com/user-attachments/assets/51d726bd-b1fe-44a3-8f4e-c1ccaa0c4d17)

**Comment by ZahraGhahremani** [comment]
It was because of a duplicate column name (NYSDOT_ref). Here are the bridge lines in this HUC.

![image](https://github.com/user-attachments/assets/b696b0d6-664a-4251-8296-bb1bb4292b76)
