### ISSUE TITLE
[5pt] `fim_pipeline` fails to run for Alaska HUCs.

### ISSUE THREAD

**Issue by ZahraGhahremani** [NOAA-OWP/inundation-mapping#1307]
With the release of the new 3Dep DEMs from USGS, some updates are needed for the `fim_pipeline`. In the previous version, we used a single CONUS DEM file that contained data for both Alaska and the contiguous U.S. However, the new CONUS DEM file no longer includes data for Alaska.
To address this, the script must be modified to handle two separate DEM files: one for CONUS and one for Alaska. Additionally, the new DEM for Alaska contains different values compared to the previous DEM that covered Alaska in the CONUS dataset. For example, the red box below shows data from the new DEM in Alaska, while the blue box shows the corresponding value in the same location from the previous CONUS file, which also covered Alaska.

## Current behavior
It fails to run for Alaska HUCs. In the latest hand version, three Alaska HUCs (19020301, 19020302, 19020602) only have branch 0, while they should have other branches as well.

## Expected behavior
Alaska HUCs should include other branches. For example, HUC `19020602` has 63 branches. 

## Screenshots
![image](https://github.com/user-attachments/assets/0c28c81f-4f57-4196-b8b2-23be483d8ac0)

**Comment by RobHanna-NOAA** [comment]
Interesting. 
- was (before new dem and pre-clip)
   -  /3dep_dems/10m_5070/fim_seamless_3dep_dem_10m_5070.vrt
   - /3dep_dems/10m_South_Alaska/23_11_07/FIM_3dep_dem_South_Alask_10m.vrt

- now:
    - /**dems**/3dep_dems/10m_5070/20240916/hand_seamless_3dep_dem_10m_5070.vrt
    - /**dems**/3dep_dems/10m_South_Alaska/20240912/FIM_3dep_dem_South_Alaska_10m.vrt

- In previous version, I did have the conus DEM to include Alaska but since then, we created Alaska, so I trimmed out Alaska from the CONUS dem as it would be the wrong CRS. Now we find Alaska only it its own dem file and vrt.
-

**Comment by RobHanna-NOAA** [comment]
oh ya.. but there is one tiny fix. I should have renamed FIM_3dep_dem_South_Alaska_10m.vrt  to hand_3dep_dem_South_Alaska_10m.vrt

**Comment by ZahraGhahremani** [comment]
In the `bash_variables` lines 12 and 13, we have two file paths for the DEM (`input_DEM` and  `input_DEM_Alaska`) but in the `run_unit_wb` we just have `input_DEM`. If we add  `input_DEM=$input_DEM_Alaska` and `input_DEM=$input_DEM` into `run_unit_wb`, it can fix the issue.

**Comment by RobHanna-NOAA** [comment]
Isn't that what we already have?
