### ISSUE TITLE
[8pt] Stage-based CatFIM creating weird boxes in gpkgs

### ISSUE THREAD

**Issue by EmilyDeardorff** [NOAA-OWP/inundation-mapping#1309]
Stage-based CatFIM has recently started creating geopackages with weird box-y shapes alongside the inundation polygons. 

## Current behavior
The stage-based CatFIM output geopackage has the expected inundation polygons with large rectangular box shapes included.

## Expected behavior
We would expect to see the smaller inundation polygon **without** the large rectangular box. 

## Screenshots
Weird boxes:
![image](https://github.com/user-attachments/assets/276bf341-3ddd-41d9-bbde-523c6fa282e6)

**Comment by EmilyDeardorff** [comment]
## Notes

- Only happening in stage-based CatFIM
- The issue is happening during or before the creation of the merged inundation tif 


## Debugging Progress (as of 10/7/24)

**Folder setup**
- _Is it caused by not clearing the folder before re-running CatFIM?_
   -> not the cause, tested with clean output folders and error still occurred 
- _Is it caused by metadata pre-pull?_
   -> not the cause, tested stage-based CatFIM with and without the metadata pre-pull and the error still occurred 

**Docker image**
- _Is it caused by new docker image?_
   -> probably not the cause, tested stage-based CatFIM on an older docker image (`fim_4:dev_20240823_6321468`) and the error still occurred

**Fiona and Pyogrio**
- _Is it caused by the addition of `engine='fiona'` in file saves?_
   -> not the cause, tested stage-based CatFIM with this commented out and the error still occurred
- _Is it caused by the addition of `gpd.options.io_engine = "pyogrio"`, added in [this commit](https://github.com/NOAA-OWP/inundation-mapping/pull/1285/commits/b999676960bd5a65f54cec29ffa1b43e6bdbab5f)?_
   -> not the cause, commented this line out of all three CatFIM scripts and the error still occurred

**NoData Values**
- _Is it caused by how we are handling nodata values?_
   -> Still testing

this nodata stuff seems to be new…? from [this commit](https://github.com/NOAA-OWP/inundation-mapping/pull/1285/commits/b999676960bd5a65f54cec29ffa1b43e6bdbab5f)

![image](https://github.com/user-attachments/assets/e0f58dc9-ab51-4d4b-a0c6-980c0a9ca381)

here, nodata is set to -1

whereas here(for stage-based), in dev, nodata is set to 10?
![image](https://github.com/user-attachments/assets/f9a65d5f-57cf-45b3-971e-e3eee5f46aac)

test with stage-based nodata val set to 10
![image](https://github.com/user-attachments/assets/6ee152b0-7858-4c1f-9135-27a66daa91f0)

it looks like the boxes are still formed with that code variation →
![image](https://github.com/user-attachments/assets/01894796-8345-48c5-9582-a86c525681a1)

**Comment by RobHanna-NOAA** [comment]
While unlikely... after Emily tries more of her code level tests, we could try taking a current docker container and manually rolling back some of the packages to see if that helps. 

Also.. Emily is likely already on this, but in `produce_tif_per_huc_per_mag_for_stage`, we are really using a rather non-conventional to do it. Maybe we can look at some similar changes for making in things like agreedem.py. `with rasterio.open(dem) as elev, rasterio.open(rivers_raster) as rivers:`  Might be worth just dumping this idea in and trying it. Obviously we don't need most of that  code in agreedem.py but it does do dem masking a bit different and might give some clues (or even a fix).

**Comment by RobHanna-NOAA** [comment]
Another idea to chase later is maybe how it mosiacs?
