### ISSUE TITLE
[8pt] Clean up levee data preprocessing .py code, check dependencies, and push to repo

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#131]
Move current NLD preprocessing code from local to repo

**Comment by BradfordBates-NOAA** [comment]
@RyanSpies-NOAA What is the status of this? Can we close?

**Comment by RyanSpies-NOAA** [comment]
@BradfordBates-NOAA Let's leave this open. We are currently using a manually downloaded version of the USACE NLD. I think it would be worthwhile to build this into the automated download and preprocessing workflow sometime soon.
