### ISSUE TITLE
[5pt] Error on Fim Performance script

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1326]
During a test for test_case_by_hydro_id.py, it fails pretty much instantly and on all hucs with:

	Found 269 test cases
	Running 269 test cases:   0%|                                                                   | 0/269 [00:00<?, ?it/s]/usr/lib/python3/dist-packages/osgeo/gdal.py:315: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
	  warnings.warn(
	AttributeError("'NoneType' object has no attribute 'GetLayer'")
	AttributeError("'NoneType' object has no attribute 'GetLayer'")
AttributeError("'NoneType' object has no attribute 'GetLayer'")

Could this be a gdal issue? We updated some packages since this was last run for 4.5.2.11.

Note: This is high priority in order to continue with the current Prod run of hand_4_5_11_1.

**Comment by mluck** [comment]
There is a missing a directory level for branch 0 here: https://github.com/NOAA-OWP/inundation-mapping/blob/dev/tools/test_case_by_hydro_id.py#L255 .

For example, this results in 
```
catchment_gpkg 
 = /data/previous_fim/hand_4_5_11_1/12030109/branches/gw_catchments_reaches_filtered_addedAttributes_crosswalked_0.gpkg'
```

but should be 
```
catchment_gpkg 
 = /data/previous_fim/hand_4_5_11_1/12030109/branches/0/gw_catchments_reaches_filtered_addedAttributes_crosswalked_0.gpkg'
```
