### ISSUE TITLE
Who to contact for AWS access credentials?

### ISSUE THREAD

**Issue by jcphill** [NOAA-OWP/inundation-mapping#1333]
I have not received a reply from either of the two email addresses listed in the README. Is there someone else I should ask?

## Current behavior
No response to emails after six days.

## Expected behavior
Response with credentials.

**Comment by RobHanna-NOAA** [comment]
Sorry about that. I assume you emailed someone on our team about it but I can help you take care of that.  Can you email me directly so I can help get you those values? I do not want to put them in this ticket.  Robert.Hanna@Noaa.gov

**Comment by jcphill** [comment]
Thanks, I've emailed you directly.

**Comment by RobHanna-NOAA** [comment]
Resolved. :)
