### ISSUE TITLE
[5pt] run_test_case fails for ESIP users due to lack of IFC data

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1337]
It was reported by Jim Philips  as he tried to use `run_test_case.py`, that if fails for ESIP users. We do not have permission to distrubute IFC data to the public.

  File "/foss_fim/tools/run_test_case.py", line 57, in huc_data                                   
       for huc in os.listdir(self.validation_data):
  FileNotFoundError: [Errno 2] No such file or directory: '/data/test_cases/ifc_test_cases/validation_data_ifc'

**Comment by mluck** [comment]
IFC has already been removed in a forthcoming version in development.
