### ISSUE TITLE
[8pt] Standardize code

### ISSUE THREAD

**Issue by mluck** [NOAA-OWP/inundation-mapping#194]
Formatting and linting code to be consistent and conform with standards (such as PEP8)

**Comment by mluck** [comment]
see #34

**Comment by BradfordBates-NOAA** [comment]
Let's treat this is an Agile Story and create sub-tasks for individual scripts. Regarding style, I vote for [PEP8](https://www.python.org/dev/peps/pep-0008/).

An example task might look like "[5pt] Update styling to PEP8 in lib/rem.py"

**Comment by BradfordBates-NOAA** [comment]
@nickchadwick-noaa Will this issue be addressed by your recent cleanup branch?

**Comment by nickchadwick-noaa** [comment]
No, this will be in the next batch of cleanup tasks. I will probably introduce a linter that will standardize all the code and future code.
