### ISSUE TITLE
Various Topics on inundation.py

### ISSUE THREAD

**Issue by fernando-aristizabal** [NOAA-OWP/inundation-mapping#233]
In the course of improving inundation.py,  we should discuss some items below:

We need to highlight the batch mode that inundation.py originally had. Batch mode was intended to serve two purposes: 

1) inundate multiple HUCs in parallel to enable more rapid generation of FIM at large scales
2) generate inundation rasters, inundation polygons, and inundation depths outputs at any HUC 4,6,8 scale regardless of the spatial processing unit that was used for fim_run.sh.

These two objectives were made possible by aggregating the three required hydrofabric files (rem*,gw_catchments*, and hydroTable.csv) into three files in the "aggregate_fim_outputs" directory of a run's output directory. While the second objective was validated for computational performance and general robustness, I didn't review in great detail to see how borders of processing units were addressed. Someone may have been done this already or not. If possible, this would be the ideal solution to issue #161 because it minimizes the processing time required to aggregate fim_run.sh outputs into any processing unit you want.

If batch mode is still deemed valuable to development and viz services, then we need to consider fixing some possible issues. 

## Current behavior
The filter mode has been recently introduced to better handle some of the masking that takes place within inundation.py. 
By loading the catchments_poly file within the __make_windows_generator function, the catchments_poly file gets reloaded every time a new job is initialized in batch mode. On line 407, if catchments_poly is already loaded it checks to see if it is a DatasetReader which is rasterio class. On line 406, catchment_poly was loaded as GeoDataFrame so the correct class should be listed on line 407 which is "gpd.geodataframe.GeoDataFrame". This causes a TypeError on line 410. 

Additionally, since the catchment_poly is already loaded and then filtered on line 414, the file is subset for only one HUC and never again which creates issues for batch mode operation.

## Expected behavior
1) We may want to consider calling mask_type "huc" something like "nhd_wbd" to denote that the NHD WBD definition is used to mask while the "filter" mask_type be called something like "fim_wbd" to better denote that the FIM water boundary is used to mask the processing units. 
    - Additionally the mask_type argument is not documented in the docstring of inundate function though it is documented in the argparse below.
2) If batch mode is continued to be supported, then we need to:
    1) aggregate the catchments with a call to ogrmerge in the aggregate_fim_outputs.sh script
    2) remove the code block on lines 404-410 of inundation.py and put those where the other inputs are loaded (line ~127, maybe?).
    3) the output of line 414 should be called something else and then that something else used on lines 416 & 417.
    4) the purpose of line 413 can be integrated into line 407 by forcing data types at loading. 
    5) consider using a fiona dataset for catchment_poly to reduce memory usage since this maybe a NWM domain sized file at some point
    6) Is setting the catchment_polygons argument as required the correct idea? You only need it for the "filter" mask_type so maybe optional is best? Maybe using argument groups within argparse functionality would be best here!? Search for that online for more information.
    7) Thoroughly test changes in inundation.py in both single HUC and batch modes now and in the future.

## Steps to replicate behavior (include URLs)

1. Run fim_run.sh for any 4 or more adjacent HUC8s (ie 12020001, *002,*003,*004,*005,*006,*007,*008)
2. aggregate_fim_outputs.sh has not been updated to include support for the vector catchments. Merge those manually by: `ogrmerge.py -f GPKG -progress -single -nln catchments -o /data/outputs/<out_dir_used>/aggregate_fim_outputs/catchments.gpkg /data/outputs/<out_dir_used>/1202000*/gw_catchments_reaches_clipped_addedAttributes_crosswalked.gpkg`
3. Acquire the aggregated [forecast file](https://drive.google.com/drive/folders/1pn3NS8dDjPSA00SJ0MRNPPsChB_2htmy) that I made which represents a file that will be outputted by viz services after bank full detection. Place the file in */<out_dir_used>/aggregate_fim_outputs/
4. Make your inundation maps: `/foss_fim/tests/inundation.py -r /data/outputs/<out_dir_used>/aggregate_fim_outputs/rem.vrt -c /data/outputs/<out_dir_used>/aggregate_fim_outputs/catchments.vrt -b /data/outputs/<out_dir_used>/aggregate_fim_outputs/catchments.gpkg -t /data/outputs/<out_dir_used>/aggregate_fim_outputs/hydroTable.csv -f /data/outputs/<out_dir_used>/aggregate_fim_outputs/merged_flows_1202_100yr.csv -m filter -i /data/temp/inun.tif -p /data/temp/inun.gpkg -d /data/temp/depths.tif -u /data/inputs/wbd/WBD_National.gpkg -l WBDHU8 -j 3`
5. Note the TypeError. Change "DatasetReader" to "gpd.geodataframe.GeoDataFrame" on line 407 and note that only one set of outputs (inun_<huc8>.tif, inun_<huc8>.gpkg, depths_<huc8>.tif)is created for one HUC.

## Close
inundation.py will likely play a central role in FIM 4 as we continue to progress on catchment boundary issues. It's important it's in tip top shape as we continue to collaborate externally. If batch mode is deemed not necessary then we should aim to deprecate it completely to clean the script up as much as possible.

**Comment by fernando-aristizabal** [comment]
Due to the pressing need of this fix for external collaboration, dev-inundation-issues feature branch has been created to address items ii and iii above. All other suggestions are pending. I relinquish control of that feature branch.

**Comment by frsalas-noaa** [comment]
@LauraKeys-NOAA
