### ISSUE TITLE
rem.py not producing HAND as expected

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#24]
## Current behavior
REM creation in FIM 3 appears to assign the minimum elevation within a pixel catchment as the reference elevation. It does not appear to have a check to ensure that the minimum elevation is along the stream centerline. One result is that inundation maps can show channels as dry despite other areas in the catchment being shown as inundated. 

Example: It has been observed in HUC 111303 where a reference elevation is picked that is far away from the stream centerline and the REM value along the stream centerline is 40 m. 

## Expected behavior
The FIM2 HAND reference elevations are along channels. Areas away from the channel that may be lower than the reference elevation are assigned a 0 HAND value. FIM maps should include the river as part of the inundated area.

## Steps to replicate behavior

1. run fim_run.sh

(Will add Google slides presentation)

**Comment by frsalas-noaa** [comment]
Since this was closed and subtasks were created, should this be archived?
