### ISSUE TITLE
[2pt] Test BARC function for FR test case sites and produce alpha eval metrics

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#344]
Current BARC function is set to only run for MS due to potential issues with small stream order results. Let's do a test case run to check for possible errors and then examine the FR alpha eval metrics.

**Comment by RyanSpies-NOAA** [comment]
@TrevorGrout-NOAA should I use the BLE benchmarks or NWS/USGS benchmark to do a FR alpha evaluation?

**Comment by TrevorGrout-NOAA** [comment]
BLE uses FR, AHPS (NWS/USGS) uses mainstems. Lets go over this together.

**Comment by rspies** [comment]
@BradfordBates-NOAA Yes - this is old and can be closed.
