### ISSUE TITLE
[5pt] Implement FIM visualization masking technique for leveed areas

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#36]
Explore options for using NLD levee area polygon to mask inundation output

**Comment by BradfordBates-NOAA** [comment]
@mluck @CarsonPruitt-NOAA @RyanSpies-NOAA Could this ticket be closed?

**Comment by CarsonPruitt-NOAA** [comment]
Yes, this has been addressed with #845.
