### ISSUE TITLE
[5pt] Modify inundation.py to ingest src_full_crosswalked.csv to facilitate future SRC testing outside of the fim_run workflow

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#364]
Based on ongoing discussions, it would be helpful to perform SRC development outside of fim_run.sh to facilitate more efficient testing and evaluation (avoids the need to run long fim_run.sh jobs). We can likely modify inundation.py to ingest the src_full_crosswalk.py instead of (or in addition to) hydroTable.csv. The src_full_crosswalked.csv contains all of the hydraulic geometry and Manning's equation inputs that would allow for on the fly modifications prior to generating inundation outputs.

Maybe some overlap with #81

**Comment by BradfordBates-NOAA** [comment]
@RyanSpies-NOAA Can this be closed?
