### ISSUE TITLE
[9pt] FIM layers in Texas are not fully being modeled out of channel (Vlab 92798)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#406]
From Marian Baker:

The NWM FIM and the R&R FIM are both underrepresenting floodplain coverage in TX for the current TX flood. Even extreme events forecast into major flooding are showing only in channel extents. Most of the available NWM FIM and R&R FIM are doing this. If you check the WPOD FIM chat: https://mail.google.com/chat/u/0/#chat/space/AAAAqP4gpfU you will see the reviews by Charlie that address this at several locations.

![image](https://user-images.githubusercontent.com/69594899/121025449-caee2e80-c76a-11eb-9fc9-ddb488728aa5.png)

![image](https://user-images.githubusercontent.com/69594899/121025469-cfb2e280-c76a-11eb-84fd-6968edefd85e.png)

![image](https://user-images.githubusercontent.com/69594899/121025497-d4779680-c76a-11eb-9f96-b4fc8f5babfe.png)

![image](https://user-images.githubusercontent.com/69594899/121025511-d80b1d80-c76a-11eb-9adb-40c81897e357.png)

![image](https://user-images.githubusercontent.com/69594899/121025533-dd686800-c76a-11eb-9a36-aa22f6c291b6.png)

**Comment by BradfordBates-NOAA** [comment]
I recommend we get the flow files from this event and use as a case study for further investigation of rating curves.

@RyanSpies-NOAA This would be a helpful case study for the technique to vary N by stage.

**Comment by RyanSpies-NOAA** [comment]
Yes - looks like an interesting case study. FIM 3_0_17_1 is currently using a Manning's n value of 0.125 for this NWM feature_id. There's potentially room to increase that, but perhaps there are other issues at play here as well.

**Comment by BradfordBates-NOAA** [comment]
@AndyCarter-NOAA Check this out

**Comment by RyanSpies-NOAA** [comment]
Link to the VLAB ticket: https://vlab.noaa.gov/redmine/issues/92798
