### ISSUE TITLE
[8pt] Alternative CatFIM method (Crane method) hardening

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#411]

**Comment by TrevorGrout-NOAA** [comment]
The feature branch associated with this feature branch is: dev-map-ahps-wse
The scripts to perform the enforced water surface elevation are: map_threshold_wse.py
An example call is:
`python3 map_threshold_wse.py -f /path/to/fim/output/directory/ -w /path/to/workspace`

File dependencies: This requires  `usgs_elev_table.csv`  and `hydroTable.csv` produced during the fim_run process. These files are required to obtain the HAND datum at the gage and then convert the rating curve to an elevation. For FIM 3_0_16_1_ms_c, this script is able to produce flow files for about ~1,200 mainstems sites. To produce comparisons at more sites, the `usgs_elev_table.csv` needs to be created for more locations. 

For the ~1,200 mainstems sites that the enforced water surface elevation approach is being mapped, only 99 sites between usgs and nws benchmark sources are evaluated. The aggregated metrics for both datasets show a slight decrease in CSI for the Action and Major categories and a slight improvement for the Minor and Moderate categories.  When looking at individual plots there are some locations that show dramatic improvement across the board and vice-versa.  

![image](https://user-images.githubusercontent.com/69653333/123669355-99183700-d801-11eb-9ef1-fa396783a2f2.png)
![image](https://user-images.githubusercontent.com/69653333/123669410-ab927080-d801-11eb-80eb-5a9dacfa6a18.png)

When looking at individual plots there are some locations that show dramatic improvement (BVDN4 - NWS) across the board and vice-versa (BLTN7 - NWS).  

![image](https://user-images.githubusercontent.com/69653333/123670448-d6c98f80-d802-11eb-878a-cee556064ccb.png)
![image](https://user-images.githubusercontent.com/69653333/123670361-c2859280-d802-11eb-9c04-ada5a4c9f636.png)

Future steps include: 
1) Deep dive into individual sites to determine if there are patterns that can be determined.
2) Change the datum used to adjust the HAND rating curve.  Currently the datum is obtained from the `dem_adj_elevation` field of the `usgs_elev_table.csv`.  Using a different datum (one of the other fields) may yield better results and may be worth experimenting with.  
![image](https://user-images.githubusercontent.com/69653333/123671295-b6e69b80-d803-11eb-9d76-11e6ae1c7d4f.png)

**Comment by TrevorGrout-NOAA** [comment]
@BradfordBates-NOAA

**Comment by TrevorGrout-NOAA** [comment]
FIM 3.0.16.1 ms c (Blue bars) are the metrics calculated using the rating-curve interpolated flows associated with the selected map for that threshold category. The selected map and associated flow may be at or slightly above the threshold value. 
![image](https://user-images.githubusercontent.com/69653333/123712242-8a4c7700-d837-11eb-8998-98b83b51bba1.png)
The dev_ewswe_again_ms (orange bar) uses the exact threshold value to back calculate a flow.  The flow (and generated maps) developed with the EWSE method should correspond exactly with the threshold elevation. The Blue bars have a flow that *may* be associated with a map that is slightly above the exact threshold value.

**Comment by TrevorGrout-NOAA** [comment]
@frsalas-noaa Does this make more sense?
