### ISSUE TITLE
Automate uploading outputs to S3 bucket via the API's Release feature

### ISSUE THREAD

**Issue by nickchadwick-noaa** [NOAA-OWP/inundation-mapping#448]

**Comment by RobHanna-NOAA** [comment]
Duplicated as a newer ticket, number [625](https://github.com/NOAA-OWP/inundation-mapping/issues/625).

**Comment by RobHanna-NOAA** [comment]
A new tool has now been created as part of [PR 664](https://github.com/NOAA-OWP/inundation-mapping/pull/664) which allows for CLI or python calls to push files/folders up to any S3 bucket including Hydroviz. In light of the fact that the API may soon become deprecated, this ticket is being closed.
