### ISSUE TITLE
[13pt] Develop tool to collate catchment attributes according to hydroid

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#527]
## Overview

We want to predict error in catchments where we have no benchmark data to compare against. We hypothesize that there is a relationship between model error and catchment attributes such as slope, landcover, sinuosity, relief, and so on. In order to test this hypothesis, we need to organize catchment attributes according to hydroid.

We need a python tool to accomplish this. Let's put the tool into `/tools`. It is important that this tool run relatively quickly (less than 10 minutes), since we will need to use it routinely (with each version change).

For this issue, let's focus on collating the following attributes into a single CSV or database, each attribute as its own column. For this Sprint, these are the minimum required attributes. If possible, though, let's also add any other attributes from the hydroTable or the synthetic rating curve tables.

- hydroid
- catchment slope
- sierra test metrics (all columns)
-- These will need to be scraped out of the sierra test outputs (consult @CarsonPruitt-NOAA if needed)
- catchment area (if scrapable from a file)
- stream order
- default Manning N
- calibrated Manning N

Other attributes we should try to add over time:

- sinuosity: work with @CarsonPruitt-NOAA
- percent of catchment that's in different landcover classes (urban, rural, etc.). This would be multiple columns/attributes. We could even try to determine these values by recurrence interval (this would be a lot of columns).
- presence of levees
- presence of bridges
- anything and everything!

Ultimately, we will want to apply some kind of multivariate regression/machine learning technique to predict error at catchments where we have no benchmark data.

## Specifics
- Make a new Python file in `/tools/` called `collate_catchment_attritutes.py`
- Add argument parsing. Minimum arguments to include: 
--  `fim_directory`: the directory of `fim_run.sh` outputs
-- `output_file` or `output_database` depending on which route we go

Reference other Python tools to see how arguments are passed in and follow the style. Use pep8 Python styling.

**Comment by BradfordBates-NOAA** [comment]
@RyanSpies-NOAA Can you think of anything else for this first pass?

**Comment by RyanSpies-NOAA** [comment]
This list looks like a good start. I just checked and @BradfordBates-NOAA was correct in saying we have the catchment area in the hydroTable --> it is variable `AREASQKM`. @CalebOliven-NOAA the `/dev-fim3/src/aggregate_fim_outputs.py` that Brian developed has code that collates/appends hydroTables together - might be helpful to get you started.

**Comment by BradfordBates-NOAA** [comment]
@CalebOliven-NOAA Please target this tool to be cross-compatible with FIM4 and FIM3

**Comment by CalebOliven-NOAA** [comment]
code for basic attributes written. Currently not displaying in the dataframe, trying to work that out. Next step will be working out the conditionality in order to include the synthetic manning N. It is not there every time, so needs a bit of checking before I include it.

**Comment by CalebOliven-NOAA** [comment]
Decide surface area stage, ie, what aggregation choice to make (mean, max, min, specific stage, etc)
or make it a parameter?

**Comment by BradfordBates-NOAA** [comment]
@CalebOliven-NOAA Let's do all of them

**Comment by CalebOliven-NOAA** [comment]
investigate pca for machine learning, to highlight influential dependent variables, adjust input data format to conform to chosen machine learning tool.
