### ISSUE TITLE
[13pt] Add usgs_gage_crosswalk.py creation to FIM4 for Sierra Testing

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/inundation-mapping#539]
FIM4 currently does not create `usgs_elev_table.csv` that is utilized in the Sierra Test (`tools/rating_curve_comparison.py`). We need to add `usgs_gage_crosswalk.py` into `src/gms/run_by_branch.sh`.

**Comment by CarsonPruitt-NOAA** [comment]
We made a joint decision to run `src/usgs_gage_crosswalk.py` at the branch level during `src/gms/run_by_branch.sh`. I'm currently testing that functionality. Next on the list is to write a script that runs at the end of 'gms_run_branch.sh' for the purpose of aggregating all of the `usgs_elev_table.csv` scattered throughout the branch directories into the higher HUC directory.
