### ISSUE TITLE
[21pt] Develop optional CatFIM technique to use direct stage-to-HAND method

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#603]
For each CatFIM flow, convert the AHPS stage value to Water Surface Elevation (WSE), then to FIM stage. Inundate the REM at the calculated FIM stage to produce the CatFIM data. This approach will remove any error that is produced by using the FIM synthetic rating curves.

**Comment by BradfordBates-NOAA** [comment]
@CarsonPruitt-NOAA Just to confirm--this issue is to rework the CatFIM technique to the "Crane Method" for FIM3 right?

**Comment by CarsonPruitt-NOAA** [comment]
Yes, that's correct. We will port this to FIM v4 later on when it's the version being used in HydroVIS.

**Comment by BradfordBates-NOAA** [comment]
@CarsonPruitt-NOAA Can you remind me what the datum accuracy threshold is during the `usgs_elev_table.csv` production?

**Comment by CarsonPruitt-NOAA** [comment]
Yes, the threshold is 1 foot. Anything with accuracy greater than that will be left out.
