### ISSUE TITLE
[8pt] HUC 04010201 bug causing hydrotable file size issue

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#617]
Appears that past several FIM3 versions have an issue with creating a very large hydrotable (~200+ gb). The table is very large because there are thousands of duplicate rows in the SRCs. Underlying root cause appears to be related to input geometry/vectors as there are numerous dem derived reaches and catchments with the same hydroid value. 

![image](https://user-images.githubusercontent.com/69868854/174317114-fb36bfb5-f583-4137-8fd2-ac6bfd4694bf.png)

hydrotable with showing duplicate rows:
![image](https://user-images.githubusercontent.com/69868854/174317477-51dcb85d-3f66-40f5-a9e4-3fc6904bb497.png)

**Comment by BradfordBates-NOAA** [comment]
Taking notes.

It appears that this bug began sometime after version 3.0.28.1 (hydroTable size = 777KB).
