### ISSUE TITLE
[13pt] FIM outputs into HydroVIS s3 bucket

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#625]
To make data transfer more smooth, we want to have the API tool upload the files needed for HydroVIS (HAND raster, catchments raster, and hydroTable). The auto-upload should first check the log files to make sure that there were no errors. We should also make sure that the files are visually checked for things that might not throw an error (like excessive file sizes). 

Files needed in s3:
- [ ] HAND raster
- [ ] catchments raster
- [ ] hydroTable.csv

**Comment by RobHanna-NOAA** [comment]
The notes say for the API tool to push it, yet it also asks that it is visually checked. The API tool is all automatted. 
So.. do we:
A) Let the API tool auto push when it is a 'production' run (but if it finds any errors in the (aka.. any that exited with a non zero exit code), then do not push?

B) Do not let the API tool push, but we just run an AWS push from command line. (might have to be from the UCS2 machine.. not sure yet)

Thoughts?

**Comment by RobHanna-NOAA** [comment]
Also.. I have not figured out where to log AWS push error yet or even how to handle that, but will do a 'think' on it.

**Comment by CarsonPruitt-NOAA** [comment]
I think the idea is for the API tool to auto-push the data to S3, and then someone on the HydroVIS side will do a check before they implement the new data in production.

**Comment by RobHanna-NOAA** [comment]
First version u sing Boto3, in a full scale usage (coping all files over to s3) was very slow. It was running successfully but was aborted after 24 hours. That is impractical in a production model.  We will re-design it using CLI and AWS sync api tool. Figuring out dynamic AWS credentials will be the hardest part.
