### ISSUE TITLE
[3pt] Look into abnormal runtimes for two FR FIM3 hucs

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#631]
HUCS 04220001 & 04160003 are both taking more than 180 minutes to complete in recent FIM3 runs. This is 50%+ longer than any of the other HUCs. Perhaps there is a valid reason for this, but potentially worth looking into for better runtimes.

![image](https://user-images.githubusercontent.com/69868854/178603975-fbaccb03-6a3e-4d29-ba03-2fe70528e500.png)

**Comment by RyanSpies-NOAA** [comment]
![image](https://user-images.githubusercontent.com/69868854/178778229-ba6adfd9-7990-4d8d-a428-fe8aff6108e3.png)

**Comment by RobHanna-NOAA** [comment]
In fim4 testing, 04220001 is no longer included as it was exclusively in Canada. 04160003 is now quite fast as it is partly Canada and now clips the Canadian part out.
