### ISSUE TITLE
[3pt] UCS2 isn't loading imports correctly based on fim4 branches as of July 2022

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#643]
As of late July 2022, some attempts were made to create docker images on UCS2 based on the latest code from dev (fim4) branch. The docker build failed a few times but ultimately did succeed without any changes (not sure why).

However, even with the new docker image on UCS2, it errors out in some places. Currently it is throwing an error of `ModuleNotFoundError: No module named 'shapely'` but it is from calls from Pandas. We may need to look at the Docker (build) file and the pipfile and pipfile.lock to see where the import problems are coming from.

Note: This problem has not been seen on dev1, dev2 or UCS3, which suggest this could be a docker engine caching problem (??? ).

For now, we may not be able to do any fim4 testing on UCS2. We can use UCS3 instead, although we should be using UCS2, as UCS3 is a shared environment.

**Comment by CarsonPruitt-NOAA** [comment]
I'm assuming this was taken care of with the recent python packages update (#652)?

**Comment by RobHanna-NOAA** [comment]
Yup.
