### ISSUE TITLE
[8pt] Identify HUCs where flow is being routed upstream and causing a thalweg notch (FIM v3.X)

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#659]
Some extreme thalweg notches are being caused by cases where HUCs route flow upstream. We need a tool that can run on FIM v3.X outputs to identify these HUCs so we can implement a fix. You can use `12110111` as a testing ground as this HUC is one where this problem is occuring.

**Comment by CarsonPruitt-NOAA** [comment]
We currently have two HUCs where we've addressed this manually in [`clip_vectors_to_wbd.py`](https://github.com/NOAA-OWP/inundation-mapping/blob/e4de4e07d5fd2ac56b46023a25aacf65f721a7db/src/clip_vectors_to_wbd.py#L135).

**Comment by CarsonPruitt-NOAA** [comment]
A good, simple approach to identifying these HUCs would be to use the first and last features in `demDerived_reaches` GPKG to sample the raw DEM. If the first reach is at a lower elevation than the last reach, we can deduce that the HUC in question has this issue.

**Comment by CalebOliven-NOAA** [comment]
"/data/previous_fim/fim_3_0_34_2_ms_c/12110111/demDerived_reaches_split_filtered_addedAttributes_crosswalked.gpkg" and
/data/inputs/nhdplus_rasters/HRNHDPlusRasters1211/elev_m.tif
as 'raw dem' and demDerived_reaches

**Comment by CalebOliven-NOAA** [comment]
![image](https://user-images.githubusercontent.com/97476664/185456697-012758cf-3eed-4957-bed3-05adfdbbb4ba.png)
Here we have an example of what may be causing the problem. In other hucs, the hydroid's go in order from edge to edge, input to output. Here are the first and last hydroids in the huc 12110111. these do not represent the edges of the huc, but rather seem to have been generated based on the water body edge.

**Comment by CalebOliven-NOAA** [comment]
Current technique to identify hucs with N(mode)/N(total) >0.9

**Comment by CalebOliven-NOAA** [comment]
[16050106, 18010209, 18010203, 12110111, 11030018, 08030208, 03010203, 02030203]

**Comment by CalebOliven-NOAA** [comment]
The list of hucs with this issue is as above. Looking for more, but this is the list at the moment.
