### ISSUE TITLE
[8pt] Prune branches that are only lakes

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#663]
There are several branches that are completely made up of lakes. We should remove these branches as early on as we can from processing to save overall time.

A good testing ground for this fix will be HUCs `05130103` and `06030002`.

**Comment by mluck** [comment]
Revised based on recursively removing downstream-most reaches with attribute `Lake != -9999`
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6616694/186720340-dfe98096-769e-429e-8f6d-fe571b724615.png">

**Comment by mluck** [comment]
And a more complicated case:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6616694/186721366-210497e6-7369-47b8-9a35-b0fce4878a2b.png">

**Comment by mluck** [comment]
Upstream ends of branches in lakes are now also trimmed. Branches that enter and exit a lake remain.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6616694/186741626-60d3355a-2872-4d2d-a020-eb714a5208fe.png">

**Comment by mluck** [comment]
Here are a few more examples:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/6616694/186744880-8b712fb9-c946-46c4-aa84-d418c74964b1.png">
<img width="849" alt="image" src="https://user-images.githubusercontent.com/6616694/186754309-f1c9907e-bd22-46bc-acf4-a6c36122e6fa.png">
