### ISSUE TITLE
[8pt] Fix reverse flow issue

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#673]
We want to fix the reversed flow issue caused by the longitudinal thalweg elevation conditioning. The root cause of the issue is NHD meandering in and out of the buffered HUC polygon as seen in the screenshot. The relevant datasets are: `NHDPlusBurnLineEvent_subset.gpkg` and `wbd_buffered.gpkg`.

![image](https://user-images.githubusercontent.com/90792257/188013322-172c0686-32c8-4a53-8168-a66f3f7828bd.png)

**Comment by CarsonPruitt-NOAA** [comment]
Currently we try to fix the issue [here](https://github.com/NOAA-OWP/inundation-mapping/blob/9897cab789922b5a35572eab3dfa1a3d1cb17fca/src/clip_vectors_to_wbd.py#L94) by identifying "threshold segments" that cross the buffered HUC boundary and removing those segments if they flow into the boundary. This, however does not account for cases where the NHD stream meanders in and out of the boundary.

We need a more robust approach that involves looking closer at each threshold segment, identifying which are not the HUC outlet, and removing all upstream segments by walking through the from/to nodes.

You can use the HUCs identified in issue #659 as test locations.

**Comment by mluck** [comment]
My understanding is that TauDEM causes the reverse flow to happen when the upstream ends of the stream network extend beyond the buffered DEM. So, I'm wondering if it would work if the stream network was trimmed by selecting all of the segments that are completely within the buffer instead of clipping the stream network at the edge of the buffer. This seems simple, but will this have a negative effect anywhere else along the processing chain?

**Comment by BradfordBates-NOAA** [comment]
This does seem logical, @mluck. And it seems like it would be a relatively easy thing to test. I think it's worth testing on this HUC to see if the behavior changes.

**Comment by mluck** [comment]
Here are a couple of comparisons using the 20m smaller buffer than the wbd_buffer to clip the stream network. There is much less difference (i.e., less thalweg notch) between the new `dem_thalwegCond` and the original `dem_meters` than the previous `dem_thalwegCond-old`.

03110205
<img width="299" alt="image" src="https://user-images.githubusercontent.com/6616694/189885788-2b5f1c96-853f-4ee0-abd5-2d9fb3111871.png">

Previous dem_thalwegCond: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6616694/189892103-dc42a73f-3695-43b2-8680-8f1113f7f83e.png">

New dem_thalwegCond: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6616694/189892198-37a31555-cb24-4641-80c6-5e3dfdb16cb3.png">

Previous rem_zeroed_masked: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6616694/189892315-103c3f42-0f06-483c-8d4f-c961ead8ccfc.png">

New rem_zeroed_masked: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6616694/189892380-7298227c-7e11-42cc-8d97-09f743131b2a.png">


12110111
On channel example: 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/6616694/189884321-da7fbc1c-a953-45f3-aa55-b0bbb5b8486f.png">

Off channel -- the old rem_zeroed_masked would take the value of the DEM: 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/6616694/189893382-e8be4ac7-e3aa-4d39-be94-23d8f2080502.png">
