### ISSUE TITLE
[5pt] Review errors from fim 4.0.11.0 BED run

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#733]
After the full output of fim 4.0.11.0 makes it to the previous fim folder, review it's errors.

There were 3 HUC errors, and a couple of branch errors.

The branch errors still need to be investigated but here are some notes on the three huc fails.

10170104
- exited with code 61  - Ryan / Rob's weird nebraska huc
- should have continued as branch zero but did not on 11.0
- It started a branch zero folder and copied the rem over.. then failed.
- Yet.. it did continue to fully process one branch ( 1167000001 ).  ?? how did it get there? If the huc failed, it should not have gone onto branch processing.
- Has only one level path and does have some remaining 1 and 2's  (which did process strangely)
- Desired behavior:  Fully process a branch zero, should not have logged any errors, then process the single level 3 branch
 
10050003

- exited with code 61
- crosses Canadian border at Eastern Montana (near Medicine Hat, Alberta).
- Abnormally  low number of streams. Initially expected it was incomplete data in the nhd flowlines file but we are not dropping nhd flowlines completely.  The only streams in that huc are not in the US area, but we will need a Dem even if there are no remaining stream ???  Not sure what do to here, but we can't leave an area off the map. Still likely missing stream data, maybe we need to recheck NWM data?
- This leaves no streams of any stream order inside the US border.
- Desired Behavior:  Not sure but we don’t want to leave a gap in our map.
 

02030201

- it is a  flat area  on long island, NY with no stream order 3's or higher
- Desired behavior:  Fully process branch zero, but recognize that no remaining stream orders exist.  We will want to at least record an error code 60 or 61 but that doesn't mean it is an error, which is why we  created 60 and 61 in the first place. Those codes allow us to recognize that we do not have an error necessarily but different type of logic processing is required later (which might mean, no further processing).

**Comment by RobHanna-NOAA** [comment]
awesome... which branch (or if dev.. commit id) did you try these at?

**Comment by mluck** [comment]
Just pushed to `dev-branch-0-no-levelpath`
