### ISSUE TITLE
[13pt] Change all CRS to EPSG 5070

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#741]
Since we've updated our input DEMs to use EPSG 5070, we want all of our calculations and output files to be in this projection as well.

**Comment by CalebOliven-NOAA** [comment]
list of involved files/scripts: not much need for analysis tools as they usually use the CRS provided. Focus on fim_run workflow for now.

**Comment by CarsonPruitt-NOAA** [comment]
Most benchmark sites do not show any difference when the CRS is changed, however both `vict2` and `dupt2` do show significant changes in test scores. Interestingly, both of these sites are in the same HUC (`12100204`)

![image](https://user-images.githubusercontent.com/90792257/208947271-2283685d-9663-4105-a29f-6c6d6ae59004.png)
![image](https://user-images.githubusercontent.com/90792257/208948397-8dbb2ec8-6e7e-4068-b84b-667d936d5c3b.png)

![image](https://user-images.githubusercontent.com/90792257/208947429-bd4a61cc-0b82-4f70-8bbb-063f396b09c4.png)
![image](https://user-images.githubusercontent.com/90792257/208948754-0937779d-bb4e-464a-8598-027e5fb7d1cd.png)

Further investigation into this HUC is required to see what's causing this discrepancy.

**Comment by mluck** [comment]
I can't seem to replicate that difference in the NE corner nor the lower CSI.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/6616694/210658913-c65de0ba-246e-4b98-afab-2d472343dcea.png">
