### ISSUE TITLE
[8pt] US Border HUC branches are throwing error 61

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#748]
Starting with BED run of 4.0.10.1, we saw a very large jump in branch errors with exit code of 61 (no remaining flowlines).  In 4.0.9.2 there were appx 60, but now are appx 1,300.  

The issue has been seen as well in 4.0.11.0 and a very recent full test BED run.

The logs and details can be seen in folders in previous_fim. 

Test border HUCs for this issue are `10060006, 04300109, 04100001`.  Both 04300109 and 04100001 are CDN border hucs and are throwing exit code of 1 (not 61) and need to be chased down.

The fix Carson and I are talking about comes with a couple of steps, first with a new input aquire and preprocess, then a new clip.

Fix steps:
1)  Pull down a large vector gkpg from the gpkg from USGS 3Dep. If I can be done programmatically, great. If not, just document in the preprocess script for this input.  The URL is http://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Elevation/13/FullExtentSpatialMetadata/FESM_13.gpkg

2) Preprocess this gkpg to dissolve all of the polygons into one, fundamentally giving us one large US border cut line which matches the 3Dep dems.  Maybe call it something like 3Dep_US_border.gkpg (or whatever).

3) Bring this in to the code as a new input source which will be consumed in clip_vectors_to_wbd.py.  At appx line 46, immediately after creating the new wbd_buffer, clip it against the new 3Dep_US_border.gkpg so the buffer no longer extend into Canada or Mexico.  Note.. we can keep using the name wbd_buffer and we just know it had Canada and Mexico erased.

4) With the new wbd_buffer file, we can adjust the wbd_streams_buffer and reduce it by the extra 3 x cellsize.  Why? This will give us a stream buffer that is 3 x cellsize smaller but also does not cross into Canada / Mexico.

Continue using the wbd_buffer as normal through the code (with Canada / Mexico erased).  This will automatically remove any flowlines that are outside the US and should solve all of the branch exit code 61 errors. This will leave us with the only remaining branch errors being 04100001- 1316000004  and 04300109 - 1020000001. Those two hucs need to be researched and fixed here as well.

**Comment by CarsonPruitt-NOAA** [comment]
Most of these new 61 errors are caused by the limited extent of the 3DEP DEMs. See here:
![image](https://user-images.githubusercontent.com/90792257/203168924-dd663802-34c3-4273-b993-e9d8ba8ef408.png)

**Comment by CarsonPruitt-NOAA** [comment]
Here is the general strategy for new streams buffer. We want to erase the areas outside of our 3DEP domain on the `wbd_buffer` geodataframe (see line 47 below). Then, using the erased `wbd_buffer` as a starting place, you should do a negative buffer to create the `wbd_streams_buffer`. This will ensure that our streams are also not pulled from outside the 3DEP domain as well as not re-introducing the thalweg notch caused by stream-DEM boundary intersections.

`/src/clip_vectors_to_wbd.py`
![image](https://user-images.githubusercontent.com/90792257/204369968-7620f8fd-c284-40ce-b062-fc3d21462573.png)

**Comment by mluck** [comment]
The edges of the DEMs don't align with the FESM grid (image below). I'm creating the outline polygon directly from the HUC6 DEMs and dissolving those instead.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/6616694/204888240-8a4e0188-6c4d-4d6e-8a24-1ec2caa6f056.png">

**Comment by RobHanna-NOAA** [comment]
The DEMs were clipped originally against the WBD HUC6's with no buffer. I kept an eye out for projections as well.
