### ISSUE TITLE
[21pt] Revise levee-protected areas algorithm to avoid "slivers" of inundation at edges of leveed areas

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#759]
Inundated areas larger than levee-protected areas often leave linear "slivers" of inundation after the levee-protected areas are masked from inundation.

**Comment by mluck** [comment]
Here's part of the REM for 12030109 branch 0 based on the levee-protected area masked DEM. In addition to the levee-protected area (gray), additional nodata area in white comes from the pixel catchment from any stream pixel within the levee-protected area.
<img width="654" alt="image" src="https://user-images.githubusercontent.com/6616694/207402532-23b7a68f-117b-4196-880c-4f0831dc877d.png">

**Comment by CarsonPruitt-NOAA** [comment]
Let's re-run the `acquire_and_preprocess.py` script to see if these missing levee polylines come in. If not, we need to look at adding the "Embankments" layer to the acquire script.

**Comment by mluck** [comment]
The dark brown is the inundation that remains after inundating at 500yr
<img width="654" alt="image" src="https://user-images.githubusercontent.com/6616694/207913589-0ddefc6f-8054-4666-a37e-5dffe4a24ebb.png">
