### ISSUE TITLE
[5pt] WBD clip for Great Lake HUCs

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#783]
The clipping of the WBD layer for HUCs on the Great Lakes may not be necessary anymore as we've changed the input streams to use the NWM network. 

[Here's the section of code where this occurs](https://github.com/NOAA-OWP/inundation-mapping/blob/e92eb8dbe6f366f98ca741b4f76c49b5516a5834/src/clip_vectors_to_wbd.py#L53)

**Comment by CarsonPruitt-NOAA** [comment]
Here's @RobHanna-NOAA notes on the issue...

- in `clip_vectors_to_wbd.py`  ( for great lakes)
    - clip `wbd` to the dem domain (good)
    - create `wbd_buffer` as `wbd` +  7,000 meters
    - If great lakes exist
        - clip `great_lakes` to `wbd_buffer`  (huc8 + 7,000)  (so `great_lakes` is  7,000 from shoreline (ish))
        - Add a buffer of `lake_buffer_distance` (20 meters).  `great_lakes` is now 6,980 from shoreline.
        - adjust wbd_buffer   (overlay) against `great_lakes` from 7,000 to 6,980 ?? 
            - Is this what we want?  Why do we bother? or do we care? We just cut back the `wbd_buffer` a little.
- in `clip_vectors_to_wbd`:  Now let's look at it from streams
    - clip `wbd` to the dem domain (good)
    - create `wbd_buffer` as `wbd` +  7,000 meters
    - create `wbd_stream_buffers` from copy of `wbd_buffer` (so huc + 7,000 m)
    - adjust` wbd_stream_buffers` to a negative buffer of (30 (3 x cellsize)) ( `wbd_stream_buffer` is now 6,790 m past huc8).
    - if great lakes exist
        - clip `great_lakes` to `wbd_buffer`  (huc8 + 7,000)  (so `great_lakes` is  7,000 from shoreline (ish))  (same as above)
        - `great_lakes_streams` clipped against `wbd_stream_buffers` (`great_lakes_stream` is 6,970 into the water)
        - `great_lakes_streams` adds a buffer for `lake_buffer_distance` (20 meters), so we are now back up to 6,990 in the water.
        - adjust `wbd_stream_buffers` (overlay) but against `great_lakes` (which is at 6,980 from shoreline), so `wbd_stream_buffer` is now also 6,980.  We lost the extra 20 meters.
            - Same questions as above. Do we care?
 
None of this matters if the nwm streams don't go that far into the water of the great lakes, or where the huc8 cuts are in relation to the great lakes.  But.. in landsea we do see some streams that go out in the water (around maine maybe others).
Again.. do we care?

**Comment by CarsonPruitt-NOAA** [comment]
@mluck Please post screenshots of the polygons that you exported here when you get a chance... thanks!

**Comment by RobHanna-NOAA** [comment]
I think Matt just adjusted his other PR for this fix. (or at least that we did not need to create the great_lakes_stream object as we don't use it.  I am not 100% on the rest.  I think we need to experiment with it as it might be assuming the relationship of where huc boundaries lie in relation to great lakes poly's.  I think some huc boundaries already go into the great lakes but some may be more/less shoreline

**Comment by CarsonPruitt-NOAA** [comment]
If Matt already has a fix in, then we can close this issue and link to the PR where that's done. Regardless, I think it's good to have this ticket to document why we're removing that section of code.

**Comment by mluck** [comment]
This was introduced in PR #375 to resolve errors related to NHDPlus HR input data. Now testing to see if we can do without that section of code now that we use NWM instead of those data using HUCs 04060101 and 04040002 in the original issue (#374).
