### ISSUE TITLE
[1pt] Inconsistent discharge in hydroTable.csv

### ISSUE THREAD

**Issue by BrianAvant** [NOAA-OWP/inundation-mapping#80]
A few HUC8s are producing inconsistent discharge in hydroTable.csv

## Current behavior
Slight deviations of CSI for HUCs 12020002, 12060102, 11140104, 13020101 are observed between different runs of the current dev branch (faf2237). It seems to be related to inconsistent discharge values in the hydro table. 

Update: flowdircond catchhydrogeo outputs

Comparing two runs of 11140104 and 13020101 on dev branch (faf2237) I observed a slight difference in the mean and standard deviation of the slope grids produced from taudem flowdircond, but it is very small (5 decimal places).

Using gdalcompare I confirmed that the input rasters to catchhydrogeo are all exact between runs except the slope grid. It uses the masked slope grid but the raster used for masking is the same as well. The resulting src_base.csv output from catchhydrogeo has inconsistent discharge values for a few specific HydroIDs. Sometimes all of the discharges will be zero and sometimes half of the stages will report zero discharge. 

Overall this only seems to affect a couple HUC8s on our BLE evaluation list and the percent change in CSI for those HUC8s are within +/- 1%.

**Comment by TrevorGrout-NOAA** [comment]
For future reference, 11110202 may also be affected.

**Comment by TrevorGrout-NOAA** [comment]
For future reference 12110110 may also be affected

**Comment by BradfordBates-NOAA** [comment]
@BrianAvant-NOAA Is this still an issue?

**Comment by BrianAvant-NOAA** [comment]
@BradfordBates-NOAA  yes.
