### ISSUE TITLE
[13pt] Stage-based CatFIM Action extents are very wide and often cover the other thresholds

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#821]
See [this vlab ticket](https://vlab.noaa.gov/redmine/issues/112684) for details. This appears to be limited to Stage-base CatFIM as Flow-based seems normal these locations. The LID in the vlab ticket is `WSTM6`, but the issue is very widespread.

The screenshot shows FIM v4 on the left and v3 on the right.
![image](https://user-images.githubusercontent.com/90792257/219804474-b9fd7bcd-1db8-46c6-a7b7-154774276d06.png)

**Comment by LauraKeys-NOAA** [comment]
Is there any way to make the original vlab ticket available for viewing (I can't access it).. based on the screenshot with this ticket, it would -appear- that the services being compared a Flow-based CatFIM and not Stage-based, so it'd be helpful to see the original! I'm not seeing problems with the individual 1-foot CatFIM outputs at that site WSTM6, but I'll check the full run to see what got added there. Also curious if it's a visualization issue with the FIM 4 version (possibly including "other / non-categorized" data in with the Action stages, or a mis-ordering of the layers as can happen in QGIS).

**Comment by CarsonPruitt-NOAA** [comment]
I'll look into why you're able to see the ticket. It's good to know that our current version doesn't have this issue. Can you include a screenshot of it here? It would also be prudent to check out what our data looks like for this version (`fim_4_0_13_1_stage_based`) to get an idea of whether there's a visualization problem going on here or just a problem with an older version of FIM.

**Comment by LauraKeys-NOAA** [comment]
I'm pulling up the latest fim_4_0_13_1_stage_based catfim results (that ran EVERYTHING), but in the meantime I already ran and visualized the stage-based catfim code for the individual site WSTM6 (in the screenshots in the original ticket, it's the northwest-most blob). It's possible that there's an issue with the full catfim results run that doesn't affect a run on an individual site, but I think the chances of that are pretty low based on the code workflow.

Here's WSTM6 shown with its Action extent, which corresponds to stage 12 feet.
![image](https://user-images.githubusercontent.com/70279180/220774896-e34cccff-603b-4aa4-ad47-1d664fd63af3.png)

If I add the stages 13-15 feet, which are still below the Minor category, it looks like this:
![image](https://user-images.githubusercontent.com/70279180/220775351-33de7a5c-8b7e-4d84-b720-dbfeb73a4460.png)

The huge extent shown in the original ticket can correspond to either the 29 foot (maximum) extent or the no-label uncategorized option.
![image](https://user-images.githubusercontent.com/70279180/220775814-ee053996-c5ad-4f59-a1d3-32e68077ce4f.png)

I'll update this ticket with definitive info about the full stage_based run.

**Comment by LauraKeys-NOAA** [comment]
Flow-based CatFIM for version 4.0.13.1 has a similar situation for the stage-based results for WSTM6 (screenshot). Action extent is reasonable, and the wide extents are for the Record category. Also worth noting is that an earlier version 4.0.9.2 is similar for the stage-based version (not shown).

![image](https://user-images.githubusercontent.com/70279180/220972942-738fbd93-9cb3-47ab-b85f-41b592892ccb.png)

**Comment by LauraKeys-NOAA** [comment]
I just checked this in the latest FIM 4.0.18.1 catfim runs, and it seems this site doesn't get included in the stage-based runs with that latest version. The flow-based data looks okay though.

**Comment by CarsonPruitt-NOAA** [comment]
Thanks for checking this one out! I talked with Corey and he confirmed that this was a HydroVIS issue. A quick re-publish of the service fixed this issue.
