### ISSUE TITLE
[13pt] Off-channel inundation caused by mis-routed flowlines

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#823]
We've observed some off-channel inundation in FIM v4. Based on Dami's analysis in #811, this may be caused by some branches that are being routed outside of the real channel. Another example is in HUC `11010013` in branch `1432000002`. FYI, I archived the flows in this screenshot here: `/data/inundation_review/archived_flow_files/20230218T0211Z_rfc_5day_max_downstream_streamflow.csv`.

![image](https://user-images.githubusercontent.com/90792257/219826257-21917b36-a716-459e-9679-5950f8bf6212.png)

**Comment by RyanSpies-NOAA** [comment]
Connected to #811

**Comment by RyanSpies-NOAA** [comment]
![image](https://user-images.githubusercontent.com/69868854/223472132-e87867ab-670b-4bb6-ac33-e04da3c680a0.png)
![image](https://user-images.githubusercontent.com/69868854/223472240-94f9e802-4afb-4212-a46b-7f2dba1260df.png)
![image](https://user-images.githubusercontent.com/69868854/223472304-02466037-fa8d-401e-b8ba-4da37c06b80f.png)

**Comment by CarsonPruitt-NOAA** [comment]
This may be unrelated, but I wanted to capture it here. 
![image](https://user-images.githubusercontent.com/90792257/223539839-444eaf6b-c382-4c59-ad63-eacc6c3be462.png)

<html>
<body>


NWM Feature ID | 2845771
-- | --
Name | Sacramento River
Hydro ID | 30930007
Stream Order | 7
USGS HUC8 | 18020104
Reference Time | 2023-03-07 18:00:00 UTC
Inherited RFC Forecast(s) | ORFC1 @ 2023-03-07 15:58:00 (action)
Max Status | Action
Max Streamflow (cfs) | 73640.96
HAND Stage (ft) | 43.34
FIM Version | 4_0_13_1
FIM Branch ID | 2858000001
Max Rating Curve Stage (ft) | 83
Max Rating Curve Streamflow (cfs) | 1273585.82
Update Time | 2023-03-07 19:17:30 UTC
oid | 667


</body>
</html>

**Comment by CarsonPruitt-NOAA** [comment]
Here's another HUC identified by @derekgiardino to add to you the testbed for this issue: `09020106`
![image](https://user-images.githubusercontent.com/90792257/231550573-8cb6c27a-a382-4dad-80e1-2ad06a3fc99c.png)

**Comment by RyanSpies-NOAA** [comment]
![image](https://user-images.githubusercontent.com/69868854/233393671-f63176b3-e1d2-4374-bd97-1101832e2930.png)
![image](https://user-images.githubusercontent.com/69868854/233393852-01529c0e-72ef-4b6b-ab0d-890149953569.png)

**Comment by CarsonPruitt-NOAA** [comment]
Can you add `08020302` to your testbed for this issue? That's the HUC that spurred the new levee algorithm that's still broken due to some mis-routed flows.
