### ISSUE TITLE
[8pt] Feature_id crosswalk

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#825]
The hydroid pictured below has been crosswalked to a feature_id on a totally different stream over a mile away.

<html>
<body>

oid | 581759
-- | --
NWM Feature ID | 4683376
Hydro ID | 11050060
USGS HUC8 | 02050302
Streamflow (cfs) | 2382.7
HAND Stage (ft) | 5.54
FIM Version | 4_0_13_1
Branch | 0

</body>
</html>

![image](https://user-images.githubusercontent.com/90792257/219828051-74fc4130-ac96-4355-9e1b-e5d70eb25812.png)

**Comment by LauraKeys-NOAA** [comment]
The crosswalk_table.csv in the previous_fim folder fim_4_0_13_1 doesn't show this combination of NWM feature ID + Hydro ID. That should be the definitive listing, right? (version 4_0_18_0 also doesn't show that combination, just for the record) To track this down further: where does this 50% AEP data and service get created? Is that something we provide, or is it hydrovis?

**Comment by CarsonPruitt-NOAA** [comment]
HydroVIS creates the AEP FIM service by inundating each HUC at the NWM retrospective recurrence intervals. The crosswalk_table.csv _should_ be definitive, but let's check the `hydroTable.csv` and the catchments geopackage (`gw_catchments..._0.gpkg`) just to be thorough.

**Comment by LauraKeys-NOAA** [comment]
The hydro ID 11050060 is paired with the feature ID 4682656 in the `crosswalk_table.csv`, in the `gw_catchments..0.gpkg`, and in the branch 0 `hydroTable.csv` on our `foss_fim` fileshare. Not sure how that feature ID 4683376 is getting matched to the hydro ID for the service, but it doesn't appear that our data is the source of the problem.

**Comment by LauraKeys-NOAA** [comment]
bringing @CoreyKrewson-NOAA into the discussion on this ticket

**Comment by CoreyKrewson-NOAA** [comment]
This is a good catch. I am looking at all our datasets and I am seeing the same thing as you so I am wondering if it is a bug in the actual inundation code. I will dig into it today

**Comment by CoreyKrewson-NOAA** [comment]
so I just reran that HUC for the AEP 50 run and I didn't get this issue again. Ill rerun the whole domain and see what if we see this issue again

**Comment by CoreyKrewson-NOAA** [comment]
I am almost done recreating the AEP FIM data. I also went through and ran some code to compare feature id with the crosswalks and no errors were found so I think the issue will be resolved after this

**Comment by CarsonPruitt-NOAA** [comment]
Thanks for confirming that the services are being crosswalked correctly, Corey. And thanks for looking into this one, Laura.
