### ISSUE TITLE
[21pt] MASTER upgrade shapely / geopandas 

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#837]
The purpose of this card is to summarize all of the shapely, pygeos, and geopandas cards that we have open and outline the tasks a bit better.

## Changes to the packages
For testing, you can upgrade these manually in your container by running `pip3 install --force-reinstall "shapely==2.0.1"`, but we should do a complete test by updating the pipfile and building a new image before merging.
```
shapely==2.0.1
geopandas==0.12.2
pandas==1.1
numba==0.56.4
rasterstats==0.18.0
rtree==1.0.1 # It's unclear whether rtree is required or not. Give it a test without first, but it may be a shapely dependency.
tqdm==4.65.0
```

Note: When I upgraded `rasterstats`, the following dependencies were also upgraded.
`affine-2.4.0 attrs-22.2.0 certifi-2022.12.7 click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.22 munch-2.5.0 numpy-1.24.2 pyparsing-3.0.9 rasterio-1.3.6 rasterstats-0.18.0 setuptools-67.5.1 shapely-2.0.1 simplejson-3.18.3 six-1.16.0 snuggs-1.4.7`

We also need to remove `pygeos` since it was merged with `shapely` in v2.

## Alterations to fim_pipeline
After running fim_pipeline with shapely v1.8, here are all of the deprecation warnings I received. You can find some details about how to fix these in the [shapely docs](https://shapely.readthedocs.io/en/stable/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable). After fixing these, we can take a look at other breaking changes that need to be fixed.

```
/foss_fim/src/clip_vectors_to_wbd.py:86: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
/foss_fim/src/clip_vectors_to_wbd.py:87: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
/foss_fim/src/clip_vectors_to_wbd.py:87: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
/foss_fim/src/clip_vectors_to_wbd.py:87: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
```

FYI I ran the following command against the logs to get this list.
`cat /data/outputs/carson_shapely_1_8/logs/unit/12090301_unit.log | grep ShapelyDeprecationWarning`

**Comment by mluck** [comment]
Additional request: Upgrade pandas to at least 1.1.0

**Comment by CarsonPruitt-NOAA** [comment]
Thanks, Matt. You're right, looks like that's a requirement for the most recent geopandas version.

**Comment by mluck** [comment]
If we want support for geoparquet in Geopandas, we may also need pyarrow: https://geopandas.org/en/stable/docs/reference/api/geopandas.read_parquet.html
