### ISSUE TITLE
[3pt] HUC error 12050006 from FIM 4.3.1.0 run

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#844]
During the FIM 4.3.1.0 BED run, one HUC failed but has no explanation on why it failed.  HUC 12050006 failed and the final output lines, which I believe are incomplete, show: 

-----------------------------------------------------------------
Clipping rasters to branches 12050006 1403000001
Sun Mar 12 04:14:29 UTC 2023
Loading file
======/outputs/fim_4_3_1_0/12050006/branch_polygons.gpkg
Number of df rows = 2

  0%|          | 0/2 [00:00<?, ?it/s]Clipping 'dem_meters_0' to branch polygons ...

 50%|█████     | 1/2 [00:07<00:07,  7.03s/it]Clipping 'flowdir_d8_burned_filled_0' to branch polygons ...

100%|██████████| 2/2 [00:10<00:00,  5.83s/it]
ETA: 0s Left: 0 AVG: 1963.00s  local:0/2/100%/2001.0s 
ETA: 0s Left: 0 AVG: 1964.00s  local:0/2/100%/2002.0s 
Command exited with non-zero status 1
	Command being timed: "/foss_fim/src/run_unit_wb.sh"

**Comment by mluck** [comment]
I ran this HUC and replicated the error in full:
```
Clipping rasters to branches 12050006 1403000001
Fri Mar 17 13:27:49 UTC 2023
Loading file
======/outputs/dev-4.3.1.0/12050006/branch_polygons.gpkg
Number of df rows = 2
  0%|          | 0/2 [00:00<?, ?it/s]Clipping 'dem_meters_0' to branch polygons ...
  0%|          | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/foss_fim/src/clip_rasters_to_branches.py", line 35, in <module>
    stream_polys.clip(raster,clipped_raster,branch_id,branch_id_attribute)
  File "/foss_fim/src/stream_branches.py", line 1137, in clip
    base,ext = out_filename_template.split('.')
ValueError: too many values to unpack (expected 2)
Command exited with non-zero status 1
	Command being timed: "/foss_fim/src/run_by_branch.sh 12050006 1403000001"
	User time (seconds): 5.96
	System time (seconds): 1.71
	Percent of CPU this job got: 60%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:12.60
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1034900
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 169
	Minor (reclaiming a frame) page faults: 224495
	Voluntary context switches: 3205
	Involuntary context switches: 191633
	Swaps: 0
	File system inputs: 35752
	File system outputs: 3360
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

***** An error has occured  *****
```

Not sure why it's only affecting this HUC and not others, but I thought the error might be the multiple `.`s in the run name (`dev-4.3.1.0`) causing problems with `base,ext = out_filename_template.split('.')` so I tried again with a different run name (`dev-4_3_1_0`) without additional `.`s) and it ran fine:
```
Clipping rasters to branches 12050006 1403000001
Fri Mar 17 15:34:50 UTC 2023
Loading file
======/outputs/dev-4_3_1_0/12050006/branch_polygons.gpkg
Number of df rows = 2
  0%|          | 0/2 [00:00<?, ?it/s]Clipping 'dem_meters_0' to branch polygons ...
 50%|█████     | 1/2 [00:06<00:06,  6.73s/it]Clipping 'flowdir_d8_burned_filled_0' to branch polygons ...
100%|██████████| 2/2 [00:10<00:00,  5.29s/it]
Cumulative Time = 0 min(s) and 14 sec
```

Using `os.path.splitext()` instead of `.split()` should fix this issue.
