### ISSUE TITLE
[13pt] Pre Clipping Vector FIM Files

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#861]
1) Pre clip all file related to `clip_vectors_to_wbd.py` and have them sitting in an input directory. Future BED runs can simply copy over the files as/when needed.

2) Pre-clip all WBD8 files (aka.. run_unit_wb.sh/"Clip WBD8" section resulting in wbd8_clp.gkg.

3) For the unit (huc) level files we end up with wbd.gkpg, wbd8_clp.gpkg and wbd_buffered.gpkg.  Do we need all three (aka.. are two of them the exact same?).

4) Calculate output sizes and runtime to see about time / costs savings / or increased storage costs.

**Comment by RobHanna-NOAA** [comment]
Mar 25, 2023 - did a quick test by commenting out some code in run_unit_wb.sh to see what the outputs sizes are and time to run. Code was set at exit 0 immediately above "derive level paths" calculations in run_unit_wb.sh.  Total run time was 8 hrs 12 mins. A normal BED run takes appx 55 hrs, so this drop a total average BED run down to appx 47 hour (ish), adjusting for not clipping but loading the pre-clipped file. Each HUC takes appx 18 min to get through these pre-clip files do to the sizes of the parent files.  Total combined output size for all 2,135 HUCs is 23 GB.

**Comment by RobHanna-NOAA** [comment]
![image](https://user-images.githubusercontent.com/90854818/227995757-c99a5bb8-8574-44e2-8486-c8b425366d68.png)

**Comment by RobHanna-NOAA** [comment]
I am well into this task but it has been deprioritized.  If we simply just want to copy all of the pre-clipped files, I already have those available which I did by commenting out portions of fim_pipeline code.  However, I assume I need to create a script to allow us to quickly rebuild these files as/if necessary.

**Comment by robgpita-noaa** [comment]
Tackling this issue, as well as the associated #862, is currently necessary to avoid Elastic File System errors when issuing a BED Domain on AWS. 2,135 Fargate containers all trying to read and keep open `$inputsDir/wbd/WBD_National.gpkg` at the same time (relatively) is causing a fatal error in our Step Function Workflow.
