### ISSUE TITLE
[2pt] Branch exit code 61 fails with temp directories

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#872]
A recent fix was put in place for this bug, PR 659, but when it was merged with the new temp directory feature, it once again fails.  `src/process_branch.sh` needs a quick adj for the temp directories for code 61. 

Examples can be seen in our previous_fim/fim_4_3_5_0/branch_errors folder

See line 40 (appx) in `src/process_branch.sh`:  rm -rf $outputRunDataDir/$hucNumber/branches/$branchId/

**Comment by CarsonPruitt-NOAA** [comment]
I think `$outputRunDataDir` just needs to be changed to `$outputDestDir`. I'm running a test for that now.

**Comment by CarsonPruitt-NOAA** [comment]
For some reason, this if block isn't catching the exit code 61. It's not removing the directory or printing "***** Branch has no valid flowlines *****". I checked v4.3.3.4 and this was happening then as well.
```
    elif [ $code -eq 61 ]; then
        echo
        err_exists=1
        echo "***** Branch has no valid flowlines *****"
        rm -rf $outputDestDir/$hucNumber/branches/$branchId/
```

Here's the end of the log file where it should be printing "***** Branch has no valid flowlines *****".
```
-----------------------------------------------------------------
Process catchments and model streams 02060001 1190000001
Wed Apr  5 21:39:07 UTC 2023
There are no flowlines in the HUC after stream order filtering.
Command exited with non-zero status 61
	Command being timed: "/foss_fim/src/run_by_branch.sh 02060001 1190000001"
	User time (seconds): 28.51
	System time (seconds): 7.09
	Percent of CPU this job got: 102%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:34.65
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 295384
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 56
	Minor (reclaiming a frame) page faults: 592752
	Voluntary context switches: 3625
	Involuntary context switches: 1354427
	Swaps: 0
	File system inputs: 0
	File system outputs: 144560
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 61

```

**Comment by RobHanna-NOAA** [comment]
Hey Carson. Do you want to keep chasing it down or would you like me to look into it.?  process_branch.sh should (well. must be made to), catch any and all errors coming out of run_by_branch.sh.
