### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Pal12344** [NOAA-OWP/inundation-mapping#927]
Edit: removed screen shot

Short description explaining the high-level reason for the new issue.
I am trying to configure AWS CLI to access the data from S3 bucket. However I have got an error as shown in the screenshot

**Comment by fernando-aristizabal** [comment]
@Pal12344 please try the full command listed on the readme:

`aws s3 ls s3://noaa-nws-owp-fim/ --request-payer requester`

**Comment by fernando-aristizabal** [comment]
@Pal12344 you also just posted you secret access keys on the open internet. I highly suggest you remove them immediately. Destroy your current IAM profile and create a new one as this one is compromised.
