### ISSUE TITLE
Downloading the data from Bucket

### ISSUE THREAD

**Issue by Pal12344** [NOAA-OWP/inundation-mapping#929]
I am trying to download the outputs by following the steps. I have assigned a path to download the outputs as mentioned in the example. 

C:\Users\abaruah>aws s3 ls s3://noaa-nws-owp-fim/ --request-payer requester
                           PRE hand_fim/
                           PRE ras2fim/

C:\Users\abaruah>aws s3 cp --recursive s3://noaa-nws-owp-fim/hand_fim/outputs/fim_4_0_18_02/12090301 C:\Users\abaruah\Hand --request-payer requester

 But I am not getting any output in the destination folder. Is it due to some  mistakes?

**Comment by mluck** [comment]
`fim_4_0_18_02` appears to be a typo in the README (we will need to get that fixed). Try changing that to `fim_4_0_18_0` in your command.

```
aws s3 ls s3://noaa-nws-owp-fim/hand_fim/ --request-payer requester
                           PRE fim_3_0_36_0/
                           PRE fim_4_0_18_0/
                           PRE fim_4_0_9_2/
                           PRE fim_4_3_11_0/
                           PRE fim_4_3_3_4/
                           PRE inputs/
                           PRE test_cases/
```

**Comment by mluck** [comment]
You may also want to use a more recent version -- 4.3.11.0 is the latest (see above).

**Comment by Pal12344** [comment]
Thank you. It worked
