### ISSUE TITLE
[8 pt] Clean up logging to make less verbose

### ISSUE THREAD

**Issue by robgpita-noaa** [NOAA-OWP/inundation-mapping#942]
For some of the larger HUCs, we are getting close to 10,000 lines of unit log output. This is cumbersome and difficult to sift through when debugging. There is also a cost associated with the size of these logs on AWS, albeit it is quite small.  

## Current behavior

There is currently a significant amount of verbosity in the logs that can be condensed.

## Expected behavior

Decrease the amount of logging output. 

## Steps to replicate behavior (include URLs)

Run `fim_pipeline.sh` and look at the log files:

`<$outputDestDir>/logs/unit/<HUC>_unit.log` file. 

`<$outputDestDir>/logs/branhc/<HUC>_branch_<branch>.log` file. 

Or if there are errors: `<$outputDestDir>/unit_errors/<HUC>_unit.log`

## Suggested fixes (starting point):

In the scripts `run_unit_wb.sh` get rid of:  `date`, `Tstart`, & `Tcount`

For all of the shorter routines, less than 20 seconds, we should remove the timing associated. 

For the routines that take a longer amount of time, leave the timing commands. 

For `run_by_branch.sh` - get rid of all of `date`, `Tstart` & `Tcount` lines, as this script takes a short amount of time to process. Remove line 3 and 4 in `run_by_branch.sh` as well. 

In `process_branch.sh` , add the following to the `tee` command: `tee --eta=never` to [suppress `ETA` log](https://unix.stackexchange.com/questions/597603/fio-how-to-reduce-verbosity). 

## Additional lines that could be removed from logs:
```
0...10...20...30...40...50...60...70...80...90...100 - done.
-----------------------------------------------------------------
Polygonize Reach Watersheds 01100003 6170000001
Split Derived Reaches 01100003 6170000001
```

**Comment by RobHanna-NOAA** [comment]
We can get rid of quite a bit of logs, but anything calling TauDEM (sometimes through mpiexec) can't be "quited" down. TauDEM has no verbosity or quiet flag options. But TauDEM is likely going away soon.
