### ISSUE TITLE
[21pt] Manual calibration of Pittsburgh reaches

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#944]
The upper reaches of HUC `05030101` near Pittsburgh are over-inundating lower flows. This is a major concern for field personnel and the upcoming public FIM release. We need to come up with a short-term, local solution until a more permanent and widespread fix can be built (e.g. Arash's transect ML routine).

@RyanSpies-NOAA and I have brainstormed and have concluded that the best course of action would be to "calibrate" the affected feature_ids by manually providing calibration coefficients to decrease Manning's n thereby narrowing flood stage and extent at lower flows. Another possible option would be for us to obtain cross-section or bathymetry data and use it to estimate cross-sectional area lost to bathymetry (I have reached out to the field to see if we can find some of this data).

You will probably need to insert this solution into the post-processing routine where calibration occurs. Ideally, the solution should be reproducible for other problem areas. I was thinking something like a CSV file that can be read in during post-processing that has columns: HUC8, feature_id, and calibration_coefficient. Feel free to explore other possible solutions and contact Ryan if you have any questions regarding calibration.

**Comment by CarsonPruitt-NOAA** [comment]
This is the reach we are interested in correcting. Blue is High Water and Yellow is 50% AEP or 2-year flood. The goal is to lessen the extent of the 50% AEP to the point where it doesn't extend much farther than the High Water, especially on the north side of the river.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/4d0ce5d6-bf07-4c2c-b09b-0a60ee81569a)

**Comment by CarsonPruitt-NOAA** [comment]
There's also a few georeferenced impact statements. Matching (or closely matching) these should be the ultimate goal. You may not have access to this service, so let me know and I can give you the data for these points.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/198ed6fb-ef1a-4a20-89b8-97f541e40f4d)

**Comment by mluck** [comment]
@CarsonPruitt-NOAA Sounds good.

As a side note, most of the over-inundation occurs in `05030101`; however, all of the georeferenced inundation points are outside that HUC. To give an idea of scale, the NWM stream reaches are uniquely colored.
<img width="595" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/a377051c-60fb-42e4-b762-a76d08fa15bf">

**Comment by mluck** [comment]
Here's an example result of the manual calibration using a 0.5 calibration coefficient

`manual_calibration_coefficients.csv`
```
HUC8,feature_id,calb_coef_manual
05030101,3824135,0.50
05030101,3824131,0.50
05030101,11050844,0.50
05030101,11050846,0.50
05030101,3786893,0.50
05030101,3786927,0.50
05032005,3786893,0.50
05020005,3786927,0.50
05010009,11050844,0.50
05010009,11050846,0.50
```

The light shade of blue is the inundation that has been reduced by manual calibration.
<img width="595" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/a3cb0163-06f5-46ce-8da1-e5e7e829621e">
