### ISSUE TITLE
Tool for processing eHydro bathy data

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#949]
The [USACE eHydro bathymetric surveys](https://www.arcgis.com/apps/dashboards/4b8f2ba307684cf597617bf1b6d2f85d) present an opportunity to calculate how much volume and bed area are missing from the USGS 3DEP data and add the missing cross-section data into the HAND synthetic rating curves.

- [x] The bathymetric data comes in TIN format. Convert it to raster.
- [x] Convert the depth raster from feet to meters
- [x] Run zonal statistics ([rasterstats](https://pythonhosted.org/rasterstats/manual.html#zonal-statistics)) to calculate missing volume per NWM feature_id
    - Vector input is the NWM catchments
    - The only statistic we need is sum 
- [ ] Calculate the bed area 
    - Calculate slope raster from depth raster
    ```
    from osgeo import gdal
    gdal.DEMProcessing('bathy_slope.tif', 'bathy_depth_meters.tif', 'slope')
    ```
    - Bed area = 1 / cos(slope * pi / 180) - 1
    - Run zonal statistics for the bed area raster as well
- [x] Divide zonal sums by length of reach
    - You may have to join to the NWM streams geopackage to get the reach lengths

**Comment by RileyMcDermott-NOAA** [comment]
QGIS Raster to Mesh:
processing.run("native:meshrasterize", {'INPUT':'ESRI_TIN:"C:/Users/riley.mcdermott/Documents/Bathymetry_PA/AL_LP_EMS_20150809_CS_005_065_SORT/AL_LP_EMS_20150809_CS_005_065_SORT_tin/tdenv9.adf"','DATASET_GROUPS':[0],'DATASET_TIME':{'type': 'static'},'EXTENT':None,'PIXEL_SIZE':1,'CRS_OUTPUT':QgsCoordinateReferenceSystem('EPSG:5070'),'OUTPUT':'C:/Users/riley.mcdermott/Documents/Bathymetry_PA/Allegheny_USACE_Depth_ft.tif'})
