### ISSUE TITLE
Bathymetry hotfix

### ISSUE THREAD

**Issue by RileyMcDermott-NOAA** [NOAA-OWP/inundation-mapping#957]
Geopackage output doesn't include Bathymetry_source column in attribute table:

line isn't working as expected:
`bathy_nwm_streams.assign(Bathymetry_source='USACE eHydro')`

replacing with:
`bathy_nwm_streams["Bathymetry_source"] = 'USACE eHydro'`

**Comment by CarsonPruitt-NOAA** [comment]
As part of this hotfix, could you also add a line after line 35 of `config/params_template.env`
```
export bathymetry_file="/data/inputs/bathymetry/bathymetry_adjustment_data.gpkg"
```

And change line 108 of `fim_post_processing.sh` to be:
```
    python3 $srcDir/bathymetric_adjustment.py -fim_dir $outputDestDir -bathy $bathymetry_file -buffer $wbd_buffer -wbd $inputsDir/wbd/WBD_National_EPSG_5070_WBDHU8_clip_dem_domain.gpkg -j $jobLimit
```
