### ISSUE TITLE
New error 61 branches

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#975]
Starting with version 4.3.12.0, we introduced more error 61 branches. Let's take a look make sure that these are legitimate branches that can be removed.

```
fim/fim_4_4_0_0/hand_datasets/08040207/branches/1943000001/hydroTable_1943000001.csv
fim/fim_4_4_0_0/hand_datasets/04140201/branches/2197000040/hydroTable_2197000040.csv
fim/fim_4_4_0_0/hand_datasets/11020009/branches/2124000001/hydroTable_2124000001.csv
fim/fim_4_4_0_0/hand_datasets/13040201/branches/3054000057/hydroTable_3054000057.csv
fim/fim_4_4_0_0/hand_datasets/13040100/branches/1131000012/hydroTable_1131000012.csv
fim/fim_4_4_0_0/hand_datasets/15050303/branches/1588000004/hydroTable_1588000004.csv
fim/fim_4_4_0_0/hand_datasets/16020310/branches/7913000004/hydroTable_7913000004.csv
fim/fim_4_4_0_0/hand_datasets/16020310/branches/9460000005/hydroTable_9460000005.csv
fim/fim_4_4_0_0/hand_datasets/18030006/branches/1715000006/hydroTable_1715000006.csv
fim/fim_4_4_0_0/hand_datasets/18050004/branches/1769000001/hydroTable_1769000001.csv
fim/fim_4_4_0_0/hand_datasets/18050004/branches/1769000005/hydroTable_1769000005.csv
```

**Comment by CarsonPruitt-NOAA** [comment]
Taking a quick look at `08040207`, branch  `1943000001` is the main branch, and probably should not be getting dropped.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/2e5ef60c-860c-410a-af55-d824408f8642)

**Comment by CarsonPruitt-NOAA** [comment]
The data outside the WBD buffer is -9999 instead of nodata. Maybe this is causing the stream to flow in the wrong direction?

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/0337e894-70b6-4e05-8bd3-732aa84243e1)

**Comment by CarsonPruitt-NOAA** [comment]
Narrowed this down to starting with version 4.3.11.2 #918. I bet `src/burn_in_levees.py` isn't handling the DEM nodata properly and is writing it out as -9999.

**Comment by robgpita-noaa** [comment]
It might be worth revisiting the amount of Exit 61 branches again. 

In `fim_4_4_2_3` there are now 280 branches with `Exit Status: 61`. 

There were 277 in `fim_4_4_0_1` and 171 in `fim_4_4_0_0`.
