### ISSUE TITLE
Check lengths of error 61 branches

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#976]
Error 61 branches are ones that we purposefully exclude from the GMS routine because they don't have large enough streamlines. We need to confirm that these are insignificant, so I would like to know the lengths of each of them.

**Comment by CarsonPruitt-NOAA** [comment]
Thanks for the nice figures! Can you identify the longest branch that's not in the list at the top of #975 and look into why that one is  erroring out? Let me know if you get stuck.

**Comment by RileyMcDermott-NOAA** [comment]
Looks like the main issue is multiple level paths being identifed as the mainstem, large sections of REM set to 0 may be causing this issue with routing. Mainstems shown below in red.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/73ced0b8-bf2d-4977-b390-8147beacec80)

Level paths identified as mainstem in red, branch error/true mainstem shown in blue, and non-mainstem stream network in yellow. Darkest green showing areas set to 0 in the REM.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/eab19642-fe13-4759-8451-c16ea93563b7)

Far up this tributary is set to 0 in the REM, causing routing issues.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/139250904/695be64a-9551-4754-9690-9f16063f9234)
