### ISSUE TITLE
[21pt] Remove GMS branch outlet backpools

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#985]
When a GMS branch flows into a larger river at its outlet, we allow it to inundate the upstream channel to show a sort of backwater effect. FIM users have expressed that the inundation in a river that doesn't have a NWM (or RFC) flow forecast above high water is confusing. Therefore, we should try to remove this effect.

The cause of this issue is the large outlet catchment that includes contributing area from the mainstem river. The screenshots below are in HUC `13080002` branch `6077000088`.

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/245a5043-2e63-4b64-b63c-60bde499d193)

![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/d2ec58b8-97c8-403e-be0e-646af0cf0cb5)

**Comment by CarsonPruitt-NOAA** [comment]
https://vlab.noaa.gov/redmine/issues/119807

**Comment by CarsonPruitt-NOAA** [comment]
My idea is to use the pixel catchments (`gw_catchments_pixels_6077000088.tif`) and identify the largest pixel catchment that occurs at the end of the DEM-derived streamline.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/630e5b40-3843-4848-add7-71cfcc5c6d50)

**Comment by CarsonPruitt-NOAA** [comment]
The PR where we trimmed the downstream end of the GMS branches is #614. This issue is somewhat related in that we want to prevent branches from inundating the mainstem rivers, but the solution will need to be different.

**Comment by EmilyDeardorff** [comment]
### Notes from tagup with Carson:

**Issue paraphrase:**

It looks like an large, erroneous catchment is being drawn at the outlet of the GMS branch. This large catchment is causing an artificially large amount of water to get routed to the smaller stream instead of the main stem, which means more of the water that could be causing flooding is coming from the small stream instead of going directly into the larger river.

The root of the issue is more in the deriving of catchments rather than the actual backwater calculations. 

The challenge here will be to figure out how to automatically choose the correct area to exclude from the HydroID catchment (i.e. the green highlighted area in the sketch).

**Potential approaches:**

- delineate and physically delete the extra catchment area, OR
- just shorten the DEM-derived streamline so the last catchment won’t include that area
    → preferred

**Related issues:**

- [Issue #560]( https://github.com/NOAA-OWP/inundation-mapping/issues/560)  is a similar issue but with downstream branches (as opposed to this one, which deals with upstream branches). It was solved in [PR #614](https://github.com/NOAA-OWP/inundation-mapping/pull/614) .


![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/8983b2c2-b670-425f-842f-b6a108d690bd)

**Comment by CarsonPruitt-NOAA** [comment]
Here's a possible strategy:

1. Get the geometry of the last vertex of the NWM branch flowline (`/13080002/nwm_subset_streams_levelPaths_dissolved.gpkg` filtered to the current `levpa_id`)
2. Use `geopandas.sjoin_nearest` with that terminal vertex and the points layer `/13080002/branches/6077000088/flows_points_pixels_6077000088`. This is very similar to what was done in #614, but better because we now have an updated version of shapely. You now should have the `id` of the point that's closest to the end of the NWM level path.
3. Load the pixel catchments TIF (`gw_catchments_pixels_6077000088.tif`) using rasterio into a numpy array and use [`numpy.unique()`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) to get the counts of each pixel catchment. IMPORTANT: the values in this raster are equal to the `id` attribute in the points layer from step 2. Load them up in QGIS to get a full understanding.
4. Now here's the tricky part. You need to create a distribution of the pixel catchment counts and choose a method to get the outlier, which is going to be that big blue pixel catchment I posted a couple comments back. You could use something like 1 or 2 standard deviations from the mean, top 5 or 10 percent -- whatever gets us that big pixel catchment. FYI for this particular branch, the value is 2404. We don't want your method to be too restrictive (top 1%) because we want it to work for all of the branches in the country, but we also don't want it to identify too many values, so you're going to have to find the Goldilocks stat.
5. Filter the values from step 4 to be less than or equal to the `id` from step 2, but greater than 100 less than that same `id`. I.e., (`id >= x > (id - 100)`). This will give you all of the outlier pixel catchment within ~1km from the outlet of the level path.
6. If there are no values returned from the range in the previous step, use the point from step 2 your trimming point.
7. If there ARE values, choose the lowest one (which will be the most upstream point) to use for your trimming.
8. Trim the downstream portion of the dem-derived stream (`demDerived_reaches_6077000088.shp`) at your selected point. You can look to Jim's PR mentioned above for how to do this using `shapely.ops.split()`.


FYI I copied the data for this HUC to our shared EFS drive: `/outputs/rio_grande/`. So, you can copy those to your EC2 and work from those instead of running pipeline yourself.

**Comment by EmilyDeardorff** [comment]
I've been experimenting with different ways of calculating the threshold for a catchment being "too big" (and therefore indicating the presence of this error).  The pixel catchments file for HUC 13080002, branch 6077000088 (`gw_catchments_pixels_6077000088.tif`) has 3,101 catchments, with the largest one (id 2404) being the error catchment that we want to remove. 

Calculating the outlier as 2 standard deviations from the mean returns 11 flagged "outlier" catchments. The distribution of the data and outliers is shown in the figure below.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/00ff5b9d-51ca-4341-9472-9d2216a0ac17)


I also looked how many rows were selected by the following methods of assigning outlier status:
 - 2 standard deviations from the mean: 11 catchments selected
 - 3 standard deviations from the mean: 10 catchments selected
 - 4 standard deviations from the mean: 10 catchments selected
 - 99th percentile: 31 catchments selected
 - 99.9th percentile: 4 catchments selected
 -  99.99th percentile: 1 catchment selected


Only the most narrow filter (99.99 percentile) selected the single erroring catchment, but it is yet to be shown whether a filter this narrow would be overly strict in other branches.

**Comment by CarsonPruitt-NOAA** [comment]
This is a great analysis... love the plot. You're spot on with the conclusion that the 99.99th percentile may be too narrow for other branches. What we want to do is add another condition that the flow point for the catchment should be close (maybe say 1km) to the end of the level path. This should eliminate the other outliers that are farther upstream and it's what I was attempting to get at with number five above, but we now know that we can't trust the `id`s to be in order, so you'll have to do a more geographic approach.

**Comment by EmilyDeardorff** [comment]
Initially, I was planning to use the ID value in the flowpoints data to indicate which point was directly upstream of the outlet (which would become the new outlet point if the branch outlet backpool issue was detected). However, the ID values do not uniformly decrease as the points go downstream. 

In the example below, you would expect the ID values (which are the numerical labels) to be lowest in the upstream part (the upper right corner) and highest in the downstream part (the lower left corner). Instead, the ID increases in some areas and actually decreases as you go downstream in others (labeled in red). 

This observation means that we should not rely on the ID value to indicate which point is upstream. 

![flows_points_pixels out of order pixels issue](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/cad06fd3-5d1a-4c25-9a4d-c74db06a93b0)

**Comment by EmilyDeardorff** [comment]
**Changing processing order:**


I moved the catch and mitigate branch outlet backpool processing out of `split_flows.py` and into a new module called `mitigate_branch_outlet_backpool.py`. This will allow the processing to take place a few steps later, after the `gw_catchment_pixels` file has been created. 

These processing steps are being run in `delineate_hydros_and_produce_HAND.sh`. The steps that take place in between `split_flows.py` and the new `mitigate_branch_outlet_backpool.py` step are: 
- Gage watershed for reaches
- Vectorize feature ID centroids
- Gage watershed for pixels (this is the step that creates the `gw_catchment_pixels` file)

**Comment by EmilyDeardorff** [comment]
**Testing the new module on HUCs 07110004 and 05010006 resulted in a LOT of flagged branches**

My concern is that a LOT of branches are getting flagged, 28/45 branches for HUC 05010006 and 30/61 branches for HUC 07110004. It seems unlikely that ~50% of the branches are exhibiting this effect. It will be necessary to gage whether these are false positives and, if so, what their impact will be. If the impact of this many false positives is estimated to be detrimental, we will need to implement a stricter selection criteria. 

This figure shows the flagged branches in red for each HUC.

![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/eb4fa6d4-abd0-4b20-8883-f57b3381e2c4)

**Comment by EmilyDeardorff** [comment]
**Effect of adding raster trimming**

As of 11/17/23, raster trimming has been added to the branch outlet backpool module. This new functionality trims the erroneous pixel catchment out of the `gw_catchment_reaches` and `gw_catchment_pixels` rasters so inundation is no longer created for the area. The effect of these changes are displayed below for branch 6077000088 of HUC 13080002. Figure 1 shows the inundation results BEFORE the raster trimming was implemented. Figure 2 shows the inundation results AFTER the raster trimming was implemented. 


Image 1: Inundation result for TEST1 (BEFORE implementing the raster trimming):
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/28733879-77b5-445c-a58a-411ed75b9700)


Image 2: Inundation result for TEST2 (after implementing the raster trimming):
![image](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/cfa6ec4b-ac9b-4d71-b8ec-8a7a2dfdbb23)

**Comment by EmilyDeardorff** [comment]
**Sensitivity analysis of the basin selection threshold**

Currently, disproportionately-large basins are flagged because they are larger than twice the standard deviation of other pixel catchments in the branch. In order to test how sensitive this process is to the standard deviation multiplier, I tested this process with standard deviation multipliers of 1 and 3 to see how much it impacts the number of branches flagged in each HUC. 

It appears that branch flagging is not very sensitive to the tested variation in the standard deviation multiplier.


![stdev_threshold](https://github.com/NOAA-OWP/inundation-mapping/assets/60829052/c3f8d7ab-5b6e-4f30-b240-20bedf67c203)
