### ISSUE TITLE
[5pt] FIM 2 MS headwater mapping

### ISSUE THREAD

**Issue by TrevorGrout-NOAA** [NOAA-OWP/inundation-mapping#99]
Multiple areas where FIM 2 MS headwater mapping appears to extend much farther upstream of FIM 3 MS.  For example 12020006 the upstream most segment for MS configuration the FIM 2 (red) vs FIM 3 (blue):
![image](https://user-images.githubusercontent.com/69653333/98127043-dba89000-1e7b-11eb-88cc-80cea1d60f19.png)

**Comment by BradfordBates-NOAA** [comment]
@TrevorGrout-NOAA Is this still important?
